Repository openshift/machine-api-operator, pull requests merged in 2018-10, with the labels that each got.

#81 Label image for release process detection
  Dockerfile
  install/image-references
  tests/e2e/manifests/images.configmap.yaml
Labels: approved, lgtm, size/M

#86 Makefile: drop verbose flag on go build
  Makefile
Labels: approved, lgtm, size/XS

#80 Run MAO in its own namespace
  cmd/machine-api-operator/main.go
  install/machineapioperator_01_images.configmap.yaml
  install/machineapioperator_02_rbac.yaml
  install/machineapioperator_03_deployment.yaml
  pkg/operator/operator.go
  pkg/render/render.go
  tests/e2e/main.go
  tests/e2e/manifests/images.configmap.yaml
  tests/e2e/manifests/operator-deployment.yaml
  tests/e2e/manifests/rbac.yaml
Labels: approved, lgtm, size/L

#87 update namespace for informers
  cmd/common/controller_context.go
  cmd/machine-api-operator/main.go
  cmd/machine-api-operator/start.go
  install/machineapioperator_00_namespace.yaml
  install/machineapioperator_01_images.configmap.yaml
  install/machineapioperator_02_rbac.yaml
  install/machineapioperator_03_deployment.yaml
  pkg/operator/operator.go
  tests/e2e/generate.sh
  tests/e2e/main.go
  tests/e2e/manifests/clusterapi-apiserver-certs.yaml
  tests/e2e/manifests/ign-config.yaml
  tests/e2e/manifests/images.configmap.yaml
  tests/e2e/manifests/mao-config.yaml
  tests/e2e/manifests/operator-deployment.yaml
  tests/e2e/manifests/rbac.yaml
Labels: approved, lgtm, size/M

#90 install: make machine api operator runlevel 50
  install/0000_50_machine-api-operator_00_namespace.yaml
  install/0000_50_machine-api-operator_01_images.configmap.yaml
  install/0000_50_machine-api-operator_02_rbac.yaml
  install/0000_50_machine-api-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#91 add specific version for images-references
  install/image-references
Labels: approved, lgtm, size/XS

#88 machines/aws/worker.machineset: Drop pubicIp
  machines/aws/worker.machineset.yaml
  pkg/render/render_test.go
Labels: approved, lgtm, size/XS

#93 Create OperatorStatus for CVO
  pkg/operator/sync.go
Labels: approved, lgtm, size/S

#94 fix rolebinding namespace
  owned-manifests/clusterapi-apiserver-role-binding.yaml
Labels: approved, lgtm, size/XS

#96 Makefile: add Go debug support for local binaries
  Makefile
Labels: approved, lgtm, size/S

#89 Add OpenStack as a supported platform
  README.md
  install/0000_50_machine-api-operator_01_images.configmap.yaml
  install/image-references
  machines/openstack/cluster.yaml
  owned-manifests/clusterapi-controller.yaml
  pkg/operator/operator.go
  pkg/operator/sync.go
  pkg/render/config.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: approved, lgtm, size/M

#98 update images
  install/0000_50_machine-api-operator_01_images.configmap.yaml
  install/0000_50_machine-api-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#99 update images
  pkg/render/render_test.go
Labels: approved, lgtm, size/XS

#102 drop pull secret
  install/0000_50_machine-api-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#101 Remove machineset and cluster objects
  cmd/common/controller_context.go
  cmd/machine-api-operator/start.go
  lib/resourceapply/clusterapi.go
  lib/resourcemerge/clusterapi.go
  lib/resourceread/clusterapi.go
  machines/aws/cluster.yaml
  machines/aws/worker.machineset.yaml
  machines/libvirt/cluster.yaml
  machines/libvirt/worker.machineset.yaml
  machines/openstack/cluster.yaml
  owned-manifests/clusterapi-manager-controllers.yaml
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  pkg/render/render_test.go
  tests/e2e/main.go
  tests/e2e/manifests/cluster.yaml
  tests/e2e/manifests/machineset.yaml
  tests/e2e/manifests/mao-config.yaml
Labels: approved, lgtm, size/XL

#105 put back 4.0 tag images
  install/0000_50_machine-api-operator_01_images.configmap.yaml
Labels: approved, lgtm, size/XS

#106 drop deprecated config. Use installer config
  install/0000_50_machine-api-operator_01_images.configmap.yaml
  owned-manifests/clusterapi-manager-controllers.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  pkg/render/config.go
  pkg/render/render.go
  pkg/render/render_test.go
  tests/e2e/main.go
  tests/e2e/manifests/install-config.yaml
  tests/e2e/manifests/mao-config.yaml
Labels: approved, lgtm, size/XL

#108 Switch logrus to glog
  owned-manifests/clusterapi-manager-controllers.yaml
Labels: approved, lgtm, size/XS
