Repository openshift/machine-api-operator, pull requests merged in 2018-08, with the labels that each got.

#13 Add unit tests for cluster and machine-set manifests
  pkg/render/render_test.go
Labels: approved, size/L

#25 Point users to `make` in README
  README.md
Labels: approved, size/XS

#26 DO NOT USE ROOT.
  README.md
Labels: approved, size/XS

#27 add optional imagebuilder
  Makefile
Labels: approved, lgtm, size/XS

#33 Copy the mao binary from the right directory
  Dockerfile
  Makefile
Labels: approved, size/XS

#29 fix doc links
  README.md
Labels: approved, retest-not-required-docs-only, size/XS

#36 Add bison to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#35 Libvirt support
  cmd/main.go
  examples/machine-api-operator-config-aws.yaml
  examples/machine-api-operator-config-libvirt.yaml
  machines/aws/cluster.yaml
  machines/aws/machine-set.yaml
  machines/cluster.yaml
  machines/libvirt/cluster.yaml
  machines/libvirt/machine-set.yaml
  machines/machine-set.yaml
  manifests/clusterapi-controller.yaml
  pkg/render/config.go
  pkg/render/machine-api-operator-config.yaml
  pkg/render/render.go
  pkg/render/render_test.go
Labels: approved, lgtm, size/XL

#34 add support for openshift actuator
  cmd/main.go
  machines/cluster.yaml
  machines/machine-set.yaml
  manifests/clusterapi-controller.yaml
  pkg/render/config.go
  pkg/render/machine-api-operator-config.yaml
  pkg/render/render_test.go
Labels: approved, size/L
