Repository openshift/machine-api-operator, pull requests merged in 2018-11, with the labels that each got.

#111 Extend RBAC role with updating status subresource
  owned-manifests/clusterapi-manager-cluster-role.yaml
Labels: approved, lgtm, size/M

#112 Nodelink controller
  cmd/nodelink-controller/main.go
  install/0000_50_machine-api-operator_01_images.configmap.yaml
  owned-manifests/clusterapi-manager-controllers.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  tests/e2e/main.go
  tests/e2e/manifests/images.configmap.yaml
  tests/e2e/util.go
Labels: approved, lgtm, size/L

#113 return err from getProviderControllerFromImages
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#115 remove unused code
  cmd/machine-api-operator/start.go
  pkg/operator/operator.go
  pkg/types/types.go
Labels: approved, lgtm, size/M

#122 Expectations
  Makefile
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/L

#123 Add operator status condition test
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/M

#118 introduce remediation
  cmd/machine-healthcheck/main.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, lgtm, size/L

#124 Nodelinktest
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/M

#126 Remove unused clients and informers
  cmd/common/client_builder.go
  cmd/common/controller_context.go
  cmd/common/helpers.go
  cmd/machine-api-operator/start.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#125 Expect reconcile
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/L

#119 deploy machine-healthcheck with mao controllers
  Dockerfile
  install/0000_50_machine-api-operator_06_machinehealthcheck.crd.yaml
  install/0000_50_machine-api-operator_07_rbac.yaml
  install/0000_50_machine-api-operator_08_deployment.yaml
  owned-manifests/clusterapi-manager-cluster-role.yaml
  owned-manifests/clusterapi-manager-controllers.yaml
  pkg/operator/config.go
  pkg/operator/operator.go
  tests/e2e/main.go
  tests/e2e/manifests/0000_50_machine-api-operator_06_machinehealthcheck.crd.yaml
Labels: approved, lgtm, size/M

#132 Move tests/e2e into test/integration
  .gitignore
  Makefile
  test/integration/README.md
  test/integration/aws.go
  test/integration/generate.sh
  test/integration/infra.tf
  test/integration/main.go
  test/integration/manifests/0000_50_machine-api-operator_02_machine.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_03_machineset.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_04_machinedeployment.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_05_cluster.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_06_machinehealthcheck.crd.yaml
  test/integration/manifests/cluster.yaml
  test/integration/manifests/ign-config.yaml
  test/integration/manifests/images.configmap.yaml
  test/integration/manifests/install-config.yaml
  test/integration/manifests/machineset.yaml
  test/integration/manifests/operator-deployment.yaml
  test/integration/manifests/rbac.yaml
  test/integration/manifests/status-crd.yaml
  test/integration/util.go
  test/integration/variables.tf
Labels: approved, lgtm, size/S

#133 Add ExpectNewNodeWhenDeletingMachine
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/L

#135 Rename config path
  install/0000_50_machine-api-operator_08_deployment.yaml
  test/integration/manifests/operator-deployment.yaml
Labels: approved, lgtm, size/XS

#140 Ensure test wait for all machines to become nodes
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/M
