Repository openshift/machine-api-operator, pull requests merged in 2018-09, with the labels that each got.

#39 Network
  examples/machine-api-operator-config-libvirt.yaml
  machines/aws/machine-set.yaml
  machines/libvirt/machine-set.yaml
  pkg/render/config.go
  pkg/render/render_test.go
Labels: approved, size/S

#40 add machineSet ami filters
  machines/aws/machine-set.yaml
  pkg/render/config.go
  pkg/render/render_test.go
Labels: approved, lgtm, size/M

#42 add go/yaml lints
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/yaml-lint.sh
  machines/aws/machine-set.yaml
  machines/libvirt/machine-set.yaml
  pkg/render/render_test.go
Labels: approved, lgtm, size/M

#41 Allow for deploying into a specific namespace
  README.md
  cmd/main.go
  examples/app-version-mao.yaml
  examples/clusterapi-apiserver-secret.yaml
  examples/machine-api-operator-config-aws.yaml
  examples/machine-api-operator-config-libvirt.yaml
  machines/aws/cluster.yaml
  machines/aws/machine-set.yaml
  machines/libvirt/cluster.yaml
  machines/libvirt/machine-set.yaml
  manifests/clusterapi-apiserver-cluster-role-binding.yaml
  manifests/clusterapi-apiserver-role-binding.yaml
  manifests/clusterapi-apiserver-svc.yaml
  manifests/clusterapi-apiserver.yaml
  manifests/clusterapi-apiservice.yaml
  manifests/clusterapi-controller-cluster-role-binding.yaml
  manifests/clusterapi-controller.yaml
  pkg/render/config.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: approved, lgtm, size/L

#45 Fix namespace when creating Cluster and MachineSet
  cmd/main.go
  examples/clusterapi-apiserver-certs.yaml
  manifests/clusterapi-apiserver.yaml
Labels: approved, lgtm, size/XS

#46 use redhat tooling image
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/S

#47 add resource library
  lib/doc.go
  lib/resourceapply/apiext.go
  lib/resourceapply/apps.go
  lib/resourceapply/clusterapi.go
  lib/resourceapply/core.go
  lib/resourceapply/rbac.go
  lib/resourcemerge/apiext.go
  lib/resourcemerge/apps.go
  lib/resourcemerge/clusterapi.go
  lib/resourcemerge/core.go
  lib/resourcemerge/meta.go
  lib/resourcemerge/meta_test.go
  lib/resourcemerge/rbac.go
  lib/resourceread/apiext.go
  lib/resourceread/apps.go
  lib/resourceread/clusterapi.go
  lib/resourceread/core.go
  lib/resourceread/rbac.go
Labels: approved, size/XXL

#50 Fix typo in libvirt cluster template
  machines/libvirt/cluster.yaml
Labels: approved, lgtm, size/XS

#51 add version to aws-actuator image
  manifests/clusterapi-controller.yaml
Labels: approved, lgtm, size/XS

#52 Use libvirt actuator image from CoreOS Quay org
  manifests/clusterapi-controller.yaml
  pkg/render/render_test.go
Labels: approved, lgtm, size/XS

#49 Main
  cmd/common/client_builder.go
  cmd/common/controller_context.go
  cmd/common/doc.go
  cmd/common/helpers.go
  cmd/main.go
  cmd/start.go
  cmd/version.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
  pkg/render/render.go
  pkg/version/version.go
  tests/e2e/main.go
Labels: approved, size/XXL

#57 Use correct IAM profile for worker machines
  hack/yaml-lint.sh
  machines/aws/machine-set.yaml
  pkg/render/render_test.go
Labels: approved, lgtm, size/XS

#60 Reconcile
  Dockerfile
  cmd/main.go
  cmd/start.go
  lib/resourceapply/apps.go
  lib/resourceapply/clusterapi.go
  lib/resourcemerge/clusterapi.go
  lib/resourcemerge/meta.go
  lib/resourceread/apiext.go
  lib/resourceread/clusterapi.go
  machines/aws/worker.machineset.yaml
  machines/libvirt/worker.machineset.yaml
  manifests/clusterapi-apiserver.yaml
  manifests/clusterapi-controller.yaml
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#63 Add vikaschoudhary16 to OWNERS
  OWNERS
Labels: size/XS

#65 clean makefile
  Makefile
Labels: approved, lgtm, size/S

#69 Makefile: fix call to go fmt check
  Makefile
Labels: approved, lgtm, size/XS

#72 Integrate node role labeling into the nodelink controller
  cmd/nodelink-controller/main.go
Labels: approved, lgtm, size/S

#75 Fix makefile
  Dockerfile
  Makefile
  cmd/machine-api-operator/main.go
  cmd/machine-api-operator/start.go
  cmd/machine-api-operator/version.go
Labels: approved, lgtm, size/XS

#77 Bake nodelink-controller into the mao docker image
  Dockerfile
Labels: approved, lgtm, size/XS

#76 Update links in README
  README.md
Labels: approved, lgtm, size/S

#74 Propagete node role through machine spec label
  cmd/nodelink-controller/main.go
Labels: approved, lgtm, size/S

#79 make golint more confident
  Makefile
Labels: approved, lgtm, size/XS

#78 Fix dockerfile to copy release manifests
  Dockerfile
  cmd/nodelink-controller/main.go
  owned-manifests/clusterapi-apiserver-cluster-role-binding.yaml
  owned-manifests/clusterapi-apiserver-role-binding.yaml
  owned-manifests/clusterapi-apiserver-svc.yaml
  owned-manifests/clusterapi-apiserver.yaml
  owned-manifests/clusterapi-apiservice.yaml
  owned-manifests/clusterapi-controller-cluster-role-binding.yaml
  owned-manifests/clusterapi-controller-cluster-role.yaml
  owned-manifests/clusterapi-controller.yaml
  pkg/operator/operator.go
  pkg/operator/sync.go
  pkg/render/render_test.go
Labels: approved, lgtm, size/M

#82 update apisever image
  install/image-references
Labels: approved, lgtm, size/XS
