Repository openshift/machine-api-operator, pull requests merged in 2019-08, with the labels that each got.

#367 Add images required for bringing up a baremetal deployment.
  install/image-references
Labels: approved, lgtm, size/S

#370 Change image reference name for ironic
  install/image-references
Labels: approved, lgtm, size/XS

#302 Integrate baremetal-operator with machine-api-operator
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_12_baremetalhost.crd.yaml
  pkg/operator/baremetal_pod.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, needs-ok-to-test, size/XL

#371 Bug 1704587: Reconcile nodes on MHC changes
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/testing/testing.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#369 Bug 1727021: Set Upgradeable condition on ClusterOperator status
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#356 Increase run-level of monitoring objects, better metric naming and new alert rule
  install/0000_90_machine-api-operator_03_servicemonitor.yaml
  install/0000_90_machine-api-operator_04_alertrules.yaml
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/M

#360 Get values for CRD's additionalPrinterColumns from annotations and labels instead of machine provider config
  Gopkg.lock
  Gopkg.toml
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
Labels: approved, lgtm, size/M

#373 Add volume type to represent shared volume for a Baremetal deployment
  install/0000_30_machine-api-operator_13_baremetalhost.crd.yaml
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm, size/S

#374 baremetal: Fix service account name.
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm, size/XS

#375 update BareMetalHost CRD
  install/0000_30_machine-api-operator_13_baremetalhost.crd.yaml
Labels: approved, lgtm, size/L

#377 baremetal: set host networking to true
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm, size/XS

#378 baremetal: Fix Ironic image names.
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm, size/S

#381 baremetal: Fix path to refresh-static-ip.
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm, size/XS

#380 baremetal: Drop ironic-exporter.
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm, size/S

#379 Set default role for minted credentials to Contributor
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/XS

#384 rbac: Allow update and patch of secrets.
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, lgtm, size/XS

#385 RBAC: Add additional metal3.io resource access
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#386 rbac: allow delete of secrets and baremetalhosts
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, lgtm, size/XS

#387 Extend makefile with 'make goimports' target
  Makefile
  hack/goimports.sh
Labels: approved, lgtm, size/S

#390 bug 1747246: nodelink_controller: fix SEGV in findNodeFromMachine()
  pkg/controller/nodelink/nodelink_controller.go
  pkg/controller/nodelink/nodelink_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#388 Bug 1744752: Add a new alert rule for reporting the Machine-api Operator failure
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M
