Repository openshift/machine-api-operator, pull requests merged in 2019-03, with the labels that each got.

#237 nodelink-controller: ensure node annotations is non nil before adding values
  cmd/nodelink-controller/main.go
Labels: approved, lgtm, size/XS

#220 Add support for kubemark
  Gopkg.lock
  Makefile
  README.md
  cmd/machine-api-operator/main.go
  config/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/kubemark-install-config.yaml
  config/kubemark.yaml
  config/kubemark_rbac.yaml
  config/kustomization.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_09_deployment.yaml
  kustomization.yaml
  pkg/operator/config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/openshift/api/config/v1/types_features.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/cluster-autoscaler-operator.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
  vendor/golang.org/x/sys/cpu/byteorder.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_arm.go
  vendor/golang.org/x/sys/cpu/cpu_gc_s390x.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo.c
  vendor/golang.org/x/sys/cpu/cpu_gccgo.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_s390x.go
  vendor/golang.org/x/sys/cpu/cpu_linux.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_ppc64x.go
  vendor/golang.org/x/sys/cpu/cpu_linux_s390x.go
  vendor/golang.org/x/sys/cpu/cpu_mips64x.go
  vendor/golang.org/x/sys/cpu/cpu_mipsx.go
  vendor/golang.org/x/sys/cpu/cpu_other_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_ppc64x.go
  vendor/golang.org/x/sys/cpu/cpu_s390x.s
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.s
Labels: approved, lgtm, size/XXL

#229 Add system-critical priority class to controller
  owned-manifests/clusterapi-manager-controllers.yaml
Labels: approved, lgtm, size/XS

#242 Fix broken links
  README.md
Labels: approved, lgtm, size/S

#241 Add additional EC2 permissions to CloudCredential request
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/S

#244 fixed typos
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#204 Get node unhealthy conditions from the ConfigMap
  README.md
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/conditions/conditions.go
  pkg/util/conditions/conditions_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/e2e_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
Labels: approved, lgtm, ok-to-test, size/XXL

#246 Don't crash when baremetal provider is used
  pkg/operator/config.go
Labels: approved, lgtm, size/S

#248 verify staleness of vendored cluster-api-actuator-pkg
  Makefile
Labels: approved, lgtm, size/XS

#249 Allow to list, watch and patch events
  install/0000_30_machine-api-operator_08_rbac.yaml
Labels: approved, lgtm, size/XS

#247 Vendor machinehealthcheck tests
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/common.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/utils.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
  vendor/k8s.io/client-go/scale/client.go
  vendor/k8s.io/client-go/scale/doc.go
  vendor/k8s.io/client-go/scale/interfaces.go
  vendor/k8s.io/client-go/scale/scheme/appsint/doc.go
  vendor/k8s.io/client-go/scale/scheme/appsint/register.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/conversion.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/doc.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/register.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta1/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/conversion.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/doc.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/register.go
  vendor/k8s.io/client-go/scale/scheme/appsv1beta2/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/conversion.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/doc.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/register.go
  vendor/k8s.io/client-go/scale/scheme/autoscalingv1/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/doc.go
  vendor/k8s.io/client-go/scale/scheme/extensionsint/doc.go
  vendor/k8s.io/client-go/scale/scheme/extensionsint/register.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/conversion.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/doc.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/register.go
  vendor/k8s.io/client-go/scale/scheme/extensionsv1beta1/zz_generated.conversion.go
  vendor/k8s.io/client-go/scale/scheme/register.go
  vendor/k8s.io/client-go/scale/scheme/types.go
  vendor/k8s.io/client-go/scale/scheme/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/scale/util.go
Labels: approved, lgtm, ok-to-test, size/XXL

#250 update credentialsrequest from v1beta1 to v1
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/XS

#252 mao: add support for 'None' provider type
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#235 Add support for managed bare metal platform.
  README.md
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm, size/M

#259 extend actuator-pkg staleness check
  Makefile
  hack/verify-actuator-pkg.sh
Labels: approved, lgtm, size/S

#260 Introduce azure support
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm, size/M

#263 Don't expose kubemark image to clusters
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
Labels: approved, lgtm, size/XS
