Repository openshift/machine-api-operator, pull requests merged in 2019-02, with the labels that each got.

#191 add back controllers using latest provider image so using machine.openshift.io
  owned-manifests/clusterapi-manager-controllers.yaml
Labels: approved, lgtm, size/S

#192 Add OpenStack deprecated image for transitioning machine API groups
  install/0000_50_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  test/integration/manifests/images.configmap.yaml
Labels: approved, do-not-merge/hold, lgtm, size/M

#194 test/e2e: fix formatting directive
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/XS

#196 Move operator weight to 30
  install/0000_30_machine-api-operator_00_namespace.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_04_machinedeployment.crd.yaml
  install/0000_30_machine-api-operator_05_cluster.crd.yaml
  install/0000_30_machine-api-operator_06_machineclass.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  install/0000_30_machine-api-operator_08_machine.crd.yaml
  install/0000_30_machine-api-operator_09_machineset.crd.yaml
  install/0000_30_machine-api-operator_10_machinedeployment.crd.yaml
  install/0000_30_machine-api-operator_11_cluster.crd.yaml
  install/0000_30_machine-api-operator_12_machineclass.crd.yaml
  install/0000_30_machine-api-operator_13_rbac.yaml
  install/0000_30_machine-api-operator_14_deployment.yaml
  test/integration/main.go
  test/integration/manifests/0000_30_machine-api-operator_02_machine.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_03_machineset.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_04_machinedeployment.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_05_cluster.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_02_machine.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_03_machineset.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_04_machinedeployment.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_05_cluster.crd.yaml
  test/integration/manifests/0000_50_machine-api-operator_07_machinehealthcheck.crd.yaml
Labels: approved, lgtm, size/S

#201 Drop deprecated controllers, update e2e to machine.openshift.io
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  owned-manifests/clusterapi-manager-controllers.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  test/e2e/main.go
  test/e2e/operator_expectations.go
  test/integration/main.go
  test/integration/manifests/0000_30_machine-api-operator_02_machine.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_03_machineset.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_04_machinedeployment.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_05_cluster.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_08_machine.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_09_machineset.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_10_machinedeployment.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_11_cluster.crd.yaml
  test/integration/manifests/cluster.yaml
  test/integration/manifests/images.configmap.yaml
  test/integration/manifests/machineset.yaml
Labels: approved, lgtm, size/L

#200 Fixup cluster operator
  Gopkg.lock
  Gopkg.toml
  install/0000_30_machine-api-operator_15_clusteroperator.yaml
  pkg/operator/status.go
  test/e2e/operator_expectations.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/type_features.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/features.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/features.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/os.go
Labels: approved, lgtm, size/XXL

#207 Drop deprecated namespace from tests
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/S

#208 Drop cluster.k8s crds
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_04_machinedeployment.crd.yaml
  install/0000_30_machine-api-operator_05_cluster.crd.yaml
  install/0000_30_machine-api-operator_05_cluster_cluster-api.crd.yaml
  install/0000_30_machine-api-operator_06_machineclass.crd.yaml
  install/0000_30_machine-api-operator_08_machine.crd.yaml
  install/0000_30_machine-api-operator_08_rbac.yaml
  install/0000_30_machine-api-operator_09_deployment.yaml
  install/0000_30_machine-api-operator_09_machineset.crd.yaml
  install/0000_30_machine-api-operator_10_clusteroperator.yaml
  install/0000_30_machine-api-operator_10_machinedeployment.crd.yaml
  install/0000_30_machine-api-operator_12_machineclass.crd.yaml
  test/integration/main.go
  test/integration/manifests/0000_30_machine-api-operator_02_machine.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_03_machineset.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_04_machinedeployment.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_05_cluster.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_08_machine.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_09_machineset.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_10_machinedeployment.crd.yaml
  test/integration/manifests/0000_30_machine-api-operator_11_cluster.crd.yaml
Labels: approved, lgtm, size/L

#209 Stop reporting unavailable when progressing and add support for multiple operands status
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
  test/integration/main.go
  test/integration/manifests/status-crd.yaml
Labels: approved, lgtm, size/L

#211 Adding new reviewers beekhof and cynepco3hahue for health check controller
  pkg/controller/machinehealthcheck/OWNERS
Labels: approved, lgtm, size/S

#206 test: say how many nodes and machines are actually expected
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/XS

#212 Delete openshift-cluster-api namespace
  install/0000_30_machine-api-operator_00_namespace_cluster-api.yaml
Labels: approved, lgtm, size/XS

#216 Remove cluster e2e test since it's not relevant for actuator
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/S

#215 manifests: update resource requirements
  owned-manifests/clusterapi-manager-controllers.yaml
Labels: approved, lgtm, size/S

#218 README.md: Fix run command in dev section.
  README.md
Labels: approved, lgtm, size/XS

#210 Move rbac up to CVO. Drop admin perms
  cmd/machine-api-operator/start.go
  install/0000_30_machine-api-operator_08_rbac.yaml
  owned-manifests/clusterapi-manager-cluster-role-binding.yaml
  owned-manifests/clusterapi-manager-cluster-role.yaml
  pkg/operator/operator.go
  pkg/operator/sync.go
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/XL

#199 Add AWS credentials request.
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/M

#219 E2e cluster api actuator pkg
  Gopkg.lock
  Gopkg.toml
  Makefile
  test/e2e/main.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/LICENSE
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/openshift/main.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/openshift/suites/e2e.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/openshift/suites/smoke_suite.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/openshift/suites/utils.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1/machineautoscaler_types.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#224 Allow for the openshift-api-manager role to create secrets
  install/0000_30_machine-api-operator_08_rbac.yaml
Labels: approved, lgtm, size/XS

#213 Rename labels from sigs.k8s.io to machine.openshift.io
  README.md
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  test/integration/aws.go
  test/integration/generate.sh
  test/integration/manifests/machineset.yaml
Labels: approved, lgtm, size/M

#225 Remove clusters.cluster.k8s.io CRD
  install/0000_30_machine-api-operator_05_cluster_cluster-api.crd.yaml
Labels: approved, lgtm, size/M

#217 MAO: Stop setting statusProgressing=true when resyincing same version
  Gopkg.lock
  pkg/operator/status.go
  pkg/operator/status_test.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_features.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduling.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
Labels: approved, lgtm, size/XXL

#233 Fix aws provider group/kind
  test/integration/manifests/machineset.yaml
Labels: approved, lgtm, size/XS

#230 Add cluster-critical priorityClass to machine-api
  install/0000_30_machine-api-operator_09_deployment.yaml
Labels: approved, lgtm, size/XS

#227 deps: switch cluster-api dependency to use master branch
  Gopkg.toml
Labels: approved, lgtm, size/XS

#228 machine-api-operator should not set limits
  install/0000_30_machine-api-operator_09_deployment.yaml
Labels: approved, lgtm, size/XS

#231 Logging and events
  cmd/machine-api-operator/helpers.go
  cmd/machine-api-operator/start.go
  cmd/nodelink-controller/main.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#236 status: report cluster operator version from payload
  install/0000_30_machine-api-operator_09_deployment.yaml
  install/0000_30_machine-api-operator_10_clusteroperator.yaml
  pkg/operator/operator.go
  pkg/operator/status.go
Labels: approved, lgtm, size/M

#238 Extend list of owners
  OWNERS
Labels: approved, lgtm
