Repository openshift/machine-api-operator, pull requests merged in 2019-05, with the labels that each got.

#306 Add machine and labels explanation
  Gopkg.lock
  README.md
  docs/examples/machine.yaml
  docs/proposals/machine-disruption-budget-kpe.md
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusterapi.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusters.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#275 Use BareMetal platform constant from openshift/api
  Gopkg.lock
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator_test.go
Labels: approved, lgtm, size/S

#312 Update README.md
  README.md
Labels: size/S

#311 Fix tolerations
  config/kubemark.yaml
  install/0000_30_machine-api-operator_09_deployment.yaml
  owned-manifests/machine-api-controllers.yaml
Labels: approved, lgtm, size/S

#313 Provide richer description of machinehealthcheck type
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
Labels: approved, lgtm, size/XS

#303 Set operator controller recorder via variable
  cmd/machine-api-operator/start.go
  pkg/operator/operator.go
Labels: 4.2, approved, lgtm, size/M

#316 Namespace flag
  cmd/machine-healthcheck/main.go
  cmd/nodelink-controller/main.go
Labels: approved, lgtm, size/S

#318 [4.1] Feature gate HC by cluster feature gate object
  pkg/operator/featuresgate.go
Labels: approved, lgtm, size/XS

#317 Feature gate HC by cluster feature gate object
  pkg/operator/featuresgate.go
Labels: approved, lgtm, size/XS

#319 Sync with cluster api 0.1.0
  Gopkg.lock
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/counter.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/event.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/cluster_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/generic.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/expansion_generated.go
Labels: approved, lgtm, size/XXL

#280 Codify operator controller
  Dockerfile
  Dockerfile.rhel7
  owned-manifests/machine-api-controllers.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: 4.2, approved, lgtm, size/XL
