Repository openshift/machine-api-operator, pull requests merged in 2019-04, with the labels that each got.

#264 operator: use infrastructure.config.openshfit.io for platformtype
  Makefile
  README.md
  config/kubemark-config-infra.yaml
  config/kubemark-install-config.yaml
  install/0000_30_machine-api-operator_08_rbac.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#266 Reuse configv1 for handling platforms
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#267 Drop azure from payload temporally
  install/image-references
Labels: approved, lgtm, size/XS

#268 Fix case of BareMetal provider type.
  pkg/operator/config.go
Labels: approved, lgtm, size/XS

#255 Drop unused labels
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
Labels: approved, lgtm, size/S

#271 Add baremetal to the machine-api-manager ClusterRole.
  install/0000_30_machine-api-operator_08_rbac.yaml
Labels: approved, lgtm, size/S

#251 Fix links to operator status and install config
  README.md
  config/machineset.yaml
Labels: approved, lgtm, size/M

#269 Add back azure image to payload
  install/image-references
Labels: approved, lgtm, size/XS

#270 Remove not yet supported CRDs
  README.md
  install/0000_30_machine-api-operator_05_cluster.crd.yaml
  install/0000_30_machine-api-operator_06_machineclass.crd.yaml
  kustomization.yaml
Labels: approved, lgtm, size/L

#272 Update LastTransitionTime at OperatorStatus Condition
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#265 Register ClusterOperator to properly generate event for the kind
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#286 Re vendor for cluster-api-actuator-pkg
  Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
Labels: approved, lgtm, size/S

#278 Better naming for controllers deployment
  Gopkg.lock
  owned-manifests/machine-api-controllers.yaml
  pkg/operator/sync.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/S

#261 mao: add support for the vsphere platform
  pkg/operator/config_test.go
  pkg/operator/operator_test.go
Labels: approved, lgtm, size/L

#283 Remove myself from OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#284 mhc: re-queue after the unhealthy node with the remaining duration
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, lgtm, size/S

#287 Use deployment client
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/S

#293 fix feature gate
  cmd/machine-api-operator/start.go
  config/0000_05_config-operator_01_featuregate.crd.yaml
  config/machine-api-operator-patch.yaml
  install/0000_30_machine-api-operator_08_rbac.yaml
  kustomization.yaml
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#294 Simplify Gopkg.toml and update vendor
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/M

#296 Reflect MetalKube rename to Metal3.
  README.md
  config/machine-api-operator-patch.yaml
  install/0000_30_machine-api-operator_08_rbac.yaml
Labels: approved, lgtm, size/S

#292 Change operator failing to degraded
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/S

#300 Add node-selector annotation to namespace
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: approved, lgtm, size/XS

#274 doc: add machine disruption budget
  docs/machine-disruption-budget-kpe.md
Labels: approved, lgtm, size/M

#305 Revendor cluster api
  Gopkg.lock
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#304 Run entire operator in tests instead of just syncClusterAPIController
  pkg/operator/operator_test.go
Labels: approved, lgtm, size/M

#308 Run make test-e2e from vendor cluster-api-actuator-pkg
  Gopkg.lock
  Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/hack/ci-integration.sh
Labels: approved, lgtm, size/S
