Repository openshift/machine-api-operator, pull requests merged in 2019-10, with the labels that each got.

#403 Disable metrics to avoid pod collisions
  cmd/machine-healthcheck/main.go
  cmd/nodelink-controller/main.go
Labels: approved, lgtm, size/S

#405 Revendor to bring cluster-api openshift/cluster-api#136 and regenerate CRDs
  go.mod
  go.sum
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/common/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/scheme/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/cluster_client.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/generated_expansion.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machineset.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machineset.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/generic.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/internalinterfaces/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/expansion_generated.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machineset.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/BUILD.bazel
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#406 Add phase field to metrics
  install/0000_90_machine-api-operator_04_alertrules.yaml
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, lgtm, size/M

#389 Create maraidb_password within the MAO for use by the baremetal IPI deployment
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#408 Switch imagePullPolicy in baremetal pod to IfNotPresent
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm, size/S

#398 Ensure the Baremetal CRD is installed before metal3 is deployed
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
  kustomization.yaml
Labels: approved, lgtm, size/XS

#411 Move unhealthy conditions list to MachineHealthCheck CRD
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
  pkg/apis/healthchecking/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/conditions/conditions.go
  pkg/util/conditions/conditions_test.go
  pkg/util/testing/testing.go
Labels: approved, lgtm, size/L

#412 Mhc refactor
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, size/XXL

#414 Add short-circuiting support and drop MDB
  cmd/machine-healthcheck/main.go
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
  pkg/apis/healthchecking/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, size/XL

#416 Remove feature gate from MHC
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, size/L

#417 Bug 1763293: pkg/operator/sync: Track lastError in waitForDeploymentRollout
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#421 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#413 Marking a couple of fields in the BaremetalHost CRD optional
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
Labels: approved, lgtm, size/XS

#422 reduce reconciling events
  cmd/machine-api-operator/start.go
  install/0000_30_machine-api-operator_11_deployment.yaml
Labels: approved, lgtm, size/S

#424 Only reconcile owned deployments
  pkg/operator/baremetal_pod.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#425 bug 1764092: fix typo logging
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#430 Revendor controller runtime
  go.mod
  go.sum
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/healthz/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/healthz/healthz.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
Labels: approved, lgtm, size/XXL
