Repository openshift/machine-api-operator, pull requests merged in 2019-07, with the labels that each got.

#299 Unit test: Verify hc feature-gate disable after enable scenario
  Gopkg.lock
  pkg/operator/operator_test.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/core.go
Labels: approved, lgtm, size/L

#339 Add GCP credential support
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/S

#341 Introduce gosec for security checks
  Makefile
  pkg/operator/config.go
  pkg/util/util.go
Labels: approved, lgtm, size/S

#342 Add prometheus CRDs for kube testing
  config/prometheusrule.crd.yaml
  config/servicemonitor.crd.yaml
  kustomization.yaml
Labels: approved, lgtm, size/XL

#336 Add updateNodeRef for node link controller
  pkg/controller/nodelink/nodelink_controller.go
  pkg/controller/nodelink/nodelink_controller_test.go
Labels: approved, lgtm, size/L

#338 Update actuator-pkg dependency
  Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/hack/go-fmt.sh
  vendor/github.com/openshift/cluster-api-actuator-pkg/hack/go-lint.sh
  vendor/github.com/openshift/cluster-api-actuator-pkg/hack/go-vet.sh
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/common.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/deloyment.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/cluster-autoscaler-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/XL

#343 Fix flaking unit test TestOperatorSync_NoOp
  pkg/operator/operator_test.go
Labels: approved, lgtm, size/M

#350 Use semantic DeepEqual for map of disrupted machines comparison
  pkg/controller/disruption/disruption.go
Labels: approved, lgtm, size/XS

#349 Remediaton strategies
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
Labels: approved, lgtm, size/L

#348 Set machine healthchecking namespace through a flag
  cmd/machine-healthcheck/main.go
  cmd/nodelink-controller/main.go
  pkg/controller/controller.go
  pkg/controller/disruption/disruption.go
  pkg/controller/disruption/disruption_test.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/nodelink/nodelink_controller.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm, size/L

#353 Make remediation strategy optional parameter
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
  pkg/apis/healthchecking/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, lgtm, size/S

#354 Add 'apps' apiGroup to daemonsets RBAC
  config/machine-api-operator-patch.yaml
Labels: approved, lgtm, size/XS

#273 Integrate machine disruption with machine health check
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
  pkg/controller/disruption/disruption.go
  pkg/controller/disruption/disruption_test.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/machines/machines.go
Labels: 4.2, approved, lgtm, size/L

#358 Decrement MD allowed count only when machine has not be previously accounted
  pkg/controller/disruption/disruption.go
  pkg/controller/disruption/disruption_test.go
Labels: approved, lgtm, size/M

#357 Add image reference to GCP machine controllers
  install/image-references
Labels: approved, lgtm, size/XS

#361 Fix nil pointer reference
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/XS

#362 credentials request: fix gcp roles
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/XS

#355 Append platform for all credentialRequest's naming for consistency
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/XS

#363 Allow reading Infrastructures from CAP*
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, lgtm, size/XS

#364 MDB: Set minimum value constraint for MinAvailable and MaxUnavailable
  install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go
Labels: approved, lgtm, size/XS

#366 Modify machine-api-controller clusterrole for daemonsets
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, lgtm, size/S
