Repository openshift/machine-api-operator, pull requests merged in 2019-12, with the labels that each got.

#442 bug 1778684: Move ExpectedMachines and CurrentHealthy to *int to differentiate null from zero when patching
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#443 Bug 1778686: Move ExpectedMachines and CurrentHealthy to *int to differentiate null from zero when patching
  pkg/apis/healthchecking/v1beta1/machinehealthcheck_types.go
  pkg/apis/healthchecking/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#445 Add CPU requests to containers
  config/machine-api-operator-deployment.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: approved, lgtm, size/S

#448 Fix package name
  pkg/apis/machine/register.go
  pkg/apis/machine/v1beta1/register.go
Labels: approved, lgtm, size/XS

#449 Machine controller fixes
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, lgtm, size/M

#452 bug 1783973: Update the image name for ironic-rhcos-downloader
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#456 Update owners file
  OWNERS
Labels: approved, lgtm, size/XS

#457 Add task reconciling and networking
  pkg/apis/vsphereprovider/v1alpha1/vsphereproviderstatus_types.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/session/session_test.go
Labels: approved, lgtm, size/XL
