Repository openshift/machine-api-operator, pull requests merged in 2019-06, with the labels that each got.

#253 Create MachineDisruptionBudget controller
  Gopkg.lock
  Gopkg.toml
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_10_deployment.yaml
  install/0000_30_machine-api-operator_11_clusteroperator.yaml
  kustomization.yaml
  pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go
  pkg/apis/healthchecking/v1alpha1/register.go
  pkg/apis/healthchecking/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_controllers.go
  pkg/controller/disruption/disruption.go
  pkg/controller/disruption/disruption_test.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/fake/fake_healthchecking_client.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/fake/fake_machinedisruptionbudget.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/healthchecking_client.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/machinedisruptionbudget.go
  pkg/util/machines/machines.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinedisruptionbudget.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: 4.2, approved, lgtm, size/XXL

#321 Nodelink
  cmd/machine-healthcheck/main.go
  cmd/nodelink-controller/controller_test.go
  cmd/nodelink-controller/main.go
  pkg/controller/add_controllers.go
  pkg/controller/controller.go
  pkg/controller/nodelink/nodelink_controller.go
  pkg/controller/nodelink/nodelink_controller_test.go
Labels: approved, lgtm, size/XXL

#315 scope down permissions to namespace
  config/machine-api-operator-patch.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_10_deployment.yaml
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#325 install: use creds-operator to create creds for MAO on Azure
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/S

#324 Add OpenStack credentials request
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm, size/S

#326 Update CVO to include https://github.com/openshift/cluster-version-operator/pull/198
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1/machineset.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/factory.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/generic.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/machineset.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/expansion_generated.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/cluster/v1alpha1/machineset.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/expansion_generated.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/machine.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/machineclass.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/machineset.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/apps.go
  vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/core.go
Labels: approved, lgtm, size/XXL

#330 Fix related objects to be included in status
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/L

#334 Switch build to go 1.12
  Dockerfile
  Dockerfile.rhel7
  Makefile
  cmd/machine-api-operator/controller_context.go
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/S

#322 Add short names for MHC and MDB custom resources
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
  pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go
  pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
Labels: approved, lgtm, needs-rebase, size/XS

#327 Move common testing methods to the separate package
  pkg/controller/disruption/disruption_test.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/testing/testing.go
Labels: approved, lgtm, size/XL

#337 Add GCP support
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm, size/S
