Repository openshift/machine-api-operator, pull requests merged in 2019-11, with the labels that each got.

#435 Add roles and clusterRoles to related resources
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/M

#436 bug 1765427: Add index for getting machines from node.
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#434 Drop mdb CRD and feature gate logic
  hack/gen-crd.sh
  hack/generate-groups.sh
  hack/update-codegen.sh
  install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
  pkg/apis/healthchecking/v1alpha1/doc.go
  pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go
  pkg/apis/healthchecking/v1alpha1/register.go
  pkg/apis/healthchecking/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/disruption/disruption.go
  pkg/controller/disruption/disruption_test.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/fake/fake_healthchecking_client.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/fake/fake_machinedisruptionbudget.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/healthchecking_client.go
  pkg/generated/clientset/versioned/typed/healthchecking/v1alpha1/machinedisruptionbudget.go
  pkg/operator/featuresgate.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  pkg/util/machines/machines.go
  pkg/util/testing/testing.go
Labels: approved, lgtm, size/XXL

#437 Add manifest annotations for hosted deployment exclusions
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_10_service.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  install/0000_30_machine-api-operator_12_clusteroperator.yaml
  install/0000_90_machine-api-operator_03_servicemonitor.yaml
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, lgtm, size/S

#441 Migrate controllers
  cmd/machineset/main.go
  go.mod
  go.sum
  pkg/controller/machine/actuator.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/errors.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machine/openshift_controller_test.go
  pkg/controller/machine/testactuator.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/controller_test.go
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/delete_policy_test.go
  pkg/controller/machineset/machine.go
  pkg/controller/machineset/machine_test.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/machineset/status.go
  pkg/controller/machineset/util.go
  pkg/controller/machineset/util_test.go
  pkg/drain/drain.go
  pkg/drain/drain_test.go
  pkg/util/retry.go
  pkg/util/util.go
  vendor/github.com/go-log/log/LICENSE
  vendor/github.com/go-log/log/README.md
  vendor/github.com/go-log/log/capture/capture.go
  vendor/github.com/go-log/log/info/info.go
  vendor/github.com/go-log/log/log.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
