Repository openshift/machine-api-operator, pull requests merged in 2020-11, with the labels that each got.

#671 Bug 1820083: configure metal3 metrics collection
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/metrics/metrics.go
  pkg/operator/baremetal_pod.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#744 [OCPCLOUD-809] Add verify-diff check in generate task and enable in CI
  Makefile
  hack/go-gen.sh
  hack/update-codegen.sh
  hack/verify-diff.sh
Labels: approved, lgtm

#746 Bug 1889620: Azure disconnected reject publicIP setting
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#627 [OCPCLOUD-937] Update resources to allow termination handler to apply conditions
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_09_security_context_constraint.yaml
  install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
  pkg/operator/sync.go
Labels: approved, lgtm

#725 Bug 1896704: Inject cluster-wide proxy configuration in to machine-api-controller deployment
  cmd/machine-api-operator/start.go
  docs/user/cluster-wide-proxy.md
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#749 Bug 1889620: Warn MachineSet with publicIp set in disconnected install
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#750 Add IBM Cloud managed annotations to CVO manifests
  install/0000_30_machine-api-operator_00_namespace.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
Labels: approved, lgtm

#745 Bug 1895838: Remove extraneous code comments
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/apis/machine/v1beta1/machineset_types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#652 [OCPCLOUD-907] Add `remediationsAllowed` field to MHC status
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/condition_consts.go
  pkg/apis/machine/v1beta1/condition_types.go
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/controller/machinehealthcheck/machinehealthcheck_status_matcher.go
  pkg/util/conditions/getter.go
  pkg/util/conditions/getter_test.go
  pkg/util/conditions/matcher.go
  pkg/util/conditions/matcher_test.go
  pkg/util/conditions/setter.go
  pkg/util/conditions/setter_test.go
Labels: approved, lgtm

#731 [OCPCLOUD-994] Add simple overview user document
  docs/user/machine-api-operator-overview.md
Labels: approved, lgtm

#733 Bug 1890456: Cleanup and refactor vSphere metrics
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#582 add more FAQ information about annotations, labels, and taints
  FAQ.md
Labels: approved, kind/documentation, lgtm

#756 [release-4.6] Bug 1896705: Inject cluster-wide proxy configuration in to machine-api-controller deployment
  cmd/machine-api-operator/start.go
  docs/user/cluster-wide-proxy.md
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#752 add mapi_machinehealthcheck_nodes_covered metric
  cmd/machine-healthcheck/main.go
  docs/dev/metrics.md
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/metrics/machinehealthcheck.go
  pkg/metrics/metrics.go
Labels: approved, lgtm

#757 update openshift/library-go
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: approved, lgtm

#754 add mapi_machinehealthcheck_remediation_success_total metric
  docs/dev/metrics.md
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/metrics/machinehealthcheck.go
Labels: approved, lgtm

#726 Add machine API hacking guide
  docs/dev/hacking-guide.md
Labels: approved, lgtm

#716 Add Kubevirt provider
  hack/push-updates.sh
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm

#761 Bug 1902157: Fix spelling of automountServiceAccountToken
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
