Repository openshift/machine-api-operator, pull requests merged in 2020-01, with the labels that each got.

#462 [OCPCLOUD-700] Add customer printer columns for MachineHealthCheck CRDs
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
Labels: approved, lgtm, size/S

#458 vsphere: Add support for passing ignition user-data
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm, size/L

#459 vsphere: set providerID
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm, size/L

#461 Vsphere delete
  pkg/controller/vsphere/actuator.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm, size/L

#460 Adding a new CRD for configuration needed for Baremetal provisioning
  install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
Labels: approved, lgtm, size/L

#467 Fixes to codegen for vsphere provider
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/apis/vsphereprovider/v1alpha1/register.go
Labels: approved, lgtm, size/S

#469 Expose a dynamic client in the Operator struct
  cmd/machine-api-operator/client_builder.go
  cmd/machine-api-operator/start.go
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#432 Add support for oVirt platform
  go.mod
  go.sum
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#427 Add support for events into MHC controller
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, lgtm, size/L

#470 Read Metal3 config from a new CRD
  cmd/machine-api-operator/client_builder.go
  cmd/machine-api-operator/start.go
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#477 pkg/controller/machinehealthcheck/OWNERS: remove frobware
  pkg/controller/machinehealthcheck/OWNERS
Labels: approved, lgtm, size/XS

#478 Pass config values read from Baremetal Provisioning CR to Metal3
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, size/L

#473 OpenStack: allow cluster-api-provider-openstack to read configmaps
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/M

#474 Vsphere provider
  Dockerfile
  Dockerfile.rhel7
  Makefile
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator_test.go
Labels: approved, lgtm, size/M

#468 Update readme to reflect controllers
  README.md
Labels: approved, lgtm, size/L

#471 vsphere: Reconcile region and zone labels on Machine
  cmd/vsphere/main.go
  go.mod
  go.sum
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/controller/vsphere/actuator.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/util.go
  vendor/github.com/vmware/govmomi/vapi/internal/internal.go
  vendor/github.com/vmware/govmomi/vapi/rest/client.go
  vendor/github.com/vmware/govmomi/vapi/tags/categories.go
  vendor/github.com/vmware/govmomi/vapi/tags/tag_association.go
  vendor/github.com/vmware/govmomi/vapi/tags/tags.go
  vendor/gopkg.in/gcfg.v1/LICENSE
  vendor/gopkg.in/gcfg.v1/README
  vendor/gopkg.in/gcfg.v1/doc.go
  vendor/gopkg.in/gcfg.v1/errors.go
  vendor/gopkg.in/gcfg.v1/read.go
  vendor/gopkg.in/gcfg.v1/scanner/errors.go
  vendor/gopkg.in/gcfg.v1/scanner/scanner.go
  vendor/gopkg.in/gcfg.v1/set.go
  vendor/gopkg.in/gcfg.v1/token/position.go
  vendor/gopkg.in/gcfg.v1/token/serialize.go
  vendor/gopkg.in/gcfg.v1/token/token.go
  vendor/gopkg.in/gcfg.v1/types/bool.go
  vendor/gopkg.in/gcfg.v1/types/doc.go
  vendor/gopkg.in/gcfg.v1/types/enum.go
  vendor/gopkg.in/gcfg.v1/types/int.go
  vendor/gopkg.in/gcfg.v1/types/scan.go
  vendor/gopkg.in/warnings.v0/LICENSE
  vendor/gopkg.in/warnings.v0/README
  vendor/gopkg.in/warnings.v0/warnings.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#479 VSphere: Provider Credentials
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm, size/M

#482 Bug 1796189: Add support for image download url in the provisioning CRD
  install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
