Repository openshift/machine-api-operator, pull requests merged in 2020-02, with the labels that each got.

#486 Bug 1797688: update description for MachineState phases
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  pkg/apis/machine/v1beta1/machine_types.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#485 [release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/M

#488 Bug 1733474: Add log message when draining the unreachable node
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#475 Bug 1800423: Apply the reboot annotation to the machine
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#490 Bug 1800314: Check if instance exists before proceeding with deletion
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#487 Bug 1797799: Remove CACHEURL as a config for metal3
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#489 Bug 1801228: Update BareMetalHost CRD
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#476 Bug 1800425: More appropriate annotation name
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#491 Bug 1802179: use generic image placeholders for install
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  install/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#492 Bug 1803736: Revert "Vsphere provider"
  Dockerfile
  Dockerfile.rhel7
  Makefile
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#496 BUG 1806438: Drop run-level
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
