Repository openshift/machine-api-operator, pull requests merged in 2020-09, with the labels that each got.

#692 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#693 Bug 1875036: remove Dockerfile.rhel7
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#694 BUG 1874861: Ensure an event is emitted when remediation is skipped
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#695 Bug 1855839: Ensure Progressing condition is stable when no updates to apply
  pkg/operator/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#684 Bug 1863810: - panic: "invalid memory address or nil pointer dereference" while resyncing
  pkg/operator/sync_test.go
  pkg/operator/webhook_configuration.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#699 Bug 1875939: vsphere - cloning a Windows 2019 (1909) template fails with Invalid operation for device '0'.
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#677 Bug 1878204: Adjust alert timing and severity
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#667 Bug 1877281: [vSphere] Don't fail when tag is not found
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#681 Bug 1878880: Fix confusing log messages about deleting Node
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#703 Bug 1880110: vSphere: Fix double create
  pkg/controller/vsphere/reconciler.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#704 Bug 1880110: Vsphere: fix clone task log
  pkg/controller/vsphere/reconciler.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#708 Bug 1870158: Enforce webhooks service reference to port 443
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#696 BUG 1875598: Ensure the Virtual Machine provider state is set to Unknown when Failed
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#697 Bug 1876680: Reduce influence of webhooks and convert some errors to non-fatal
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#710 Bug 1880110: vSphere: create requeue delay
  pkg/controller/vsphere/actuator.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#707 Bug 1870158: Use mergo to merge webhooks instead of custom apply
  go.mod
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  pkg/operator/webhook_configuration.go
  pkg/operator/webhook_configuration_helper.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#715 Bug 1881703: Revert "Update default user data to be worker-user-data-managed"
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
