Repository openshift/machine-api-operator, pull requests merged in 2020-07, with the labels that each got.

#618 Bug 1845610: Windows VM MachineSet error on Azure
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#600 [vSphere] Use envtest for testing machine patch
  pkg/controller/vsphere/machine_scope_test.go
Labels: approved, lgtm, release/4.6

#615 [OCPCLOUD-892] Add defaulting/validation for MachineSet ProviderSpecs
  cmd/machineset/main.go
  go.mod
  go.sum
  install/0000_30_machine-api-operator_08_webhook.yaml
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
  pkg/apis/machine/v1beta1/v1beta1_suite_test.go
  vendor/github.com/openshift/cluster-api-provider-gcp/LICENSE
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#628 Enable termination handler for GCP
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator_test.go
Labels: approved, lgtm

#605 Bug 1843327: [vSphere] Improve provider spec validation
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#629 node-linker: fix log msg in the machine indexer
  pkg/controller/nodelink/nodelink_controller.go
Labels: approved, lgtm

#630 Add MachineHealthCheck and BareMetalHost to related objects
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm

#633 Require region to be set on AWS ProviderSpec
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, lgtm

#634 Clarify shortcomings of not having MachineDeployments
  FAQ.md
Labels: approved, lgtm

#637 add a section to metrics doc on how to scrape
  docs/dev/metrics.md
Labels: approved, kind/documentation, lgtm

#571 OCPCLOUD-492: Leader election for machineSets, nodelink, vsphere and healthchecks
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/operator/sync.go
Labels: approved, lgtm, release/4.6

#626 Make webhooks operator manageable
  cmd/machine-api-operator/start.go
  cmd/machineset/main.go
  go.mod
  install/0000_30_machine-api-operator_08_webhook.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
  pkg/apis/machine/v1beta1/v1beta1_suite_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  pkg/operator/webhook_configuration.go
  pkg/operator/webhook_configuration_helper.go
Labels: approved, lgtm

#644 Bug 1857175: enforce clusterID label via webhook and preserve old behaviour in the backend
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#647 Fix panic in deployment rollout, if it was accedentially removed
  pkg/operator/sync.go
Labels: approved, lgtm

#649 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#648 Fix terminationhandler sync
  pkg/operator/operator.go
Labels: approved, lgtm

#643 Update provider dependencies
  go.mod
  go.sum
  vendor/github.com/hashicorp/golang-lru/go.mod
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/procfs/arp.go
  vendor/github.com/prometheus/procfs/buddyinfo.go
  vendor/github.com/prometheus/procfs/cpuinfo.go
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/internal/util/parse.go
  vendor/github.com/prometheus/procfs/internal/util/sysreadfile.go
  vendor/github.com/prometheus/procfs/internal/util/sysreadfile_compat.go
  vendor/github.com/prometheus/procfs/internal/util/valueparser.go
  vendor/github.com/prometheus/procfs/net_softnet.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_fdinfo.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/schedstat.go
  vendor/github.com/prometheus/procfs/vm.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/google.golang.org/appengine/README.md
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/google.golang.org/appengine/internal/net.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#641 update the baremetalhost crd for bootmode and rootdevicehints
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
Labels: approved, lgtm

#631 Enable termination handler for Azure
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator_test.go
Labels: approved, lgtm

#609 Enable prometheus metrics for controllers
  install/0000_90_machine-api-operator_03_servicemonitor.yaml
Labels: approved, lgtm

#651 BUG 1859221: Wait for resources to roll out on every sync
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#653 bug 1857175: Let webhook only set clusterID label if it does not exist
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#646 add trusted ca bundle to machine-controllers
  install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/modules.txt
Labels: approved, lgtm

#650 [OCPCLOUD-911] Add OpenAPI Validation for MHC Timeout fields and MaxUnhealthy field
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/testing/testing.go
Labels: approved, lgtm

#661 Bug 1854142: update baremetalhost crd to apiextensions.k8s.io/v1
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
