Repository openshift/machine-api-operator, pull requests merged in 2020-03, with the labels that each got.

#495 Bug 1804635: Fix timeout formatting
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#481 Update URL for CAPO repository
  README.md
Labels: approved, lgtm, size/XS

#503 Bug 1809333: ROKS - remove machine related CRDs from cluster
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#505 Add JoelSpeed as Owner
  OWNERS
Labels: approved, lgtm, size/XS

#501 [OCPCLOUD-774] Add Node startup timeout API field
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, lgtm, size/L

#510 Bring vsphere back
  Dockerfile
  Dockerfile.rhel7
  Makefile
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator_test.go
Labels: approved, lgtm, size/M

#502 BUG 1806438: Remove explicit securityContext and add granular securitycontextconstraints "use" permissions in machine-api-controllers clusterRole
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#507 Don't oscillate between Degraded and Progressing status
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/L

#509 Add unit tests for vsphere reconciler
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm, size/L

#513 BUG 1807125: Add GCP roles/compute.loadBalancerAdmin role
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#517 Remove bison from OWNERS file
  OWNERS
  pkg/controller/machinehealthcheck/OWNERS
Labels: approved, lgtm

#520 Remove unusued code and cleanup
  cmd/machine-healthcheck/main.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/operator/operator_test.go
  pkg/operator/status_test.go
Labels: approved, lgtm

#521 Add Interruptible Instance label name
  pkg/controller/machine/controller.go
Labels: approved, lgtm

#527 add elmiko to owners file
  OWNERS
Labels: approved, lgtm

#526 Fix typo in interruptible instance label
  pkg/controller/machine/controller.go
Labels: approved, lgtm

#528 BUG 1812800: Fix vSphere image link
  install/0000_30_machine-api-operator_01_images.configmap.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#529 ROKS - fix typo in CRD annotation
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
Labels: approved, lgtm

#493 fix the master ci config link in readme
  README.md
Labels: approved, lgtm, size/XS

#494 update deployment link on readme
  README.md
Labels: approved, lgtm, size/XS

#483 proposals - summary had incorrect spelling
  docs/proposals/machine-disruption-budget-kpe.md
Labels: approved, lgtm, size/XS

#524 Bug 1812862: Allow Int in String within MHC MaxUnhealthy
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#532 vSphere: Add InternalDNS with virtual machine name to Status addresses
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm

#530 Bug 1811161: ROKS - remove machine related CRDs from cluster [4.4]
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#533 Bug 1815680: Allow MachineHealthCheck to have an empty selector
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#531 Bug 1814092: ROKS: remove machine related CRDs from cluster [4.3]
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#535 [OCPCLOUD-803] Run Spot Termination Handler from Machine API Operator
  cmd/machine-api-operator/start.go
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm

#537 vsphere ipi: add extra config key with guestinfo hostname
  pkg/controller/vsphere/reconciler.go
Labels: approved, lgtm

#519 Set vSphere provider status during reconcile
  pkg/apis/vsphereprovider/v1alpha1/vsphereproviderstatus_types.go
  pkg/apis/vsphereprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/util.go
Labels: approved, lgtm

#541 Properly apply updates to MAO-managed workloads
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, lgtm

#542 Give friendly hint when not starting in-cluster
  cmd/machine-api-operator/client_builder.go
Labels: approved, lgtm

#543 bug 1816398: Let MHC to remediate any machine owned by a controller
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/testing/testing.go
Labels: approved, bugzilla/valid-bug, lgtm
