Repository openshift/machine-api-operator, pull requests merged in 2020-06, with the labels that each got.

#598 add faq question about ClusterAutoscaler and MachineAutoscaler
  FAQ.md
Labels: approved, kind/documentation, lgtm, release/4.6

#595 pkg/operator/status: Change ReasonEmpty to ReasonAsExpected
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, release/4.6

#577 fix case on annotations
  FAQ.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only

#604 [vSphere] Reduce sync period to 10 minutes
  cmd/vsphere/main.go
Labels: approved, lgtm

#576 add a link to the FAQ in the README
  README.md
Labels: approved, kind/documentation, lgtm

#610 Drop clusterID defaulting label
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, lgtm

#570 Bump controller-runtime to latest
  go.mod
  go.sum
  hack/gen-crd.sh
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/nodelink/nodelink_controller.go
  pkg/controller/nodelink/nodelink_controller_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, lgtm, release/4.6

#608 Set clusterID label on machine
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
Labels: approved, lgtm

#614 Improve testing of AWS validation webhook
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, lgtm

#587 Add dgrigore to approvers
  OWNERS
Labels: approved, lgtm

#607 [OCPCLOUD-882] Add defaulting and validation via Webhook for Azure
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#581 Allow external remediation even if there's no controller owner
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
Labels: approved, lgtm, ok-to-test

#616 Allow the Azure UserDataSecret Namespace to be omitted
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, lgtm

#611 [OCPCLOUD-881] Add defaulting and validation via Webhook for GCP
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-gcp/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#588 README.md: Link to Bugzilla "Cloud Compute"
  README.md
Labels: approved, lgtm

#590 Re-enable metrics, add metrics for vSphere
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/vsphere/main.go
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_10_service.yaml
  pkg/controller/vsphere/reconciler.go
  pkg/metrics/metrics.go
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm, release/4.6

#594 [vSphere] Add tests for machine events
  pkg/controller/vsphere/actuator.go
  pkg/controller/vsphere/actuator_test.go
Labels: approved, lgtm

#539 [release-4.4] Bug 1816606: Allow Int in String within MHC MaxUnhealthy
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#621 [vSphere] Add check for nil motask
  pkg/controller/vsphere/reconciler.go
Labels: approved, lgtm

#625 OWNERS: Add a component link for BZ
  OWNERS
Labels: approved, lgtm

#602 Add liveness/readiness probes
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/vsphere/main.go
  pkg/operator/sync.go
Labels: approved, lgtm

#613 [OCPCLOUD-883] Add defaulting and validation via Webhook for vSphere
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, lgtm

#623 Bug 1844986: Do not send Machine deletion event if the Machine has already been deleted
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
