Repository openshift/machine-api-operator, pull requests merged in 2020-10, with the labels that each got.

#711 Bug 1880110: vSphere: preserve taskID in local cache
  cmd/vsphere/main.go
  pkg/controller/vsphere/actuator.go
  pkg/controller/vsphere/actuator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#714 Bug 1883497: Fix missing logs due to mixed klog versions
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/vsphereprovider/v1beta1/register.go
  pkg/controller/machine/controller.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/machine.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/machineset/status.go
  pkg/controller/nodelink/nodelink_controller.go
  pkg/controller/nodelink/nodelink_controller_test.go
  pkg/controller/vsphere/actuator.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/session/session.go
  pkg/metrics/metrics.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/register.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#687 add tool for pushing vendor updates to consuming repos easier
  hack/push-updates.sh
Labels: approved, lgtm

#719 Bug 1876469: Fix MHC annotation and update generated artifacts
  hack/update-codegen.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/register.go
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/apis/machine/v1beta1/machineset_types.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/apis/vsphereprovider/apis.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/listers/machine/v1beta1/machine.go
  pkg/generated/listers/machine/v1beta1/machinehealthcheck.go
  pkg/generated/listers/machine/v1beta1/machineset.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#664 Bug 1864352: Add leader election mechanism to release 4.5
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#718 Bug 1880343: Bump K8s dependencies to v0.18.9
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#721 Add TroubleShooting Guide
  docs/user/TroubleShooting.md
Labels: approved, lgtm

#640 [OCPCLOUD-910] Add HistogramVector to track transition into different Machine phases
  pkg/controller/machine/controller.go
  pkg/metrics/metrics.go
Labels: approved, lgtm

#730 Bug 1884632: Bump Azure dependency to include BYOK encryption fields
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#717 Add documentation section for 'mapi_instance_OP_failed' metrics
  docs/dev/metrics.md
Labels: approved, lgtm

#735 vSphere: Enter Failed phase on invalid configuration
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
Labels: approved, lgtm

#738 add current profile annotations to CVO manifests
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_00_namespace.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
  install/0000_30_machine-api-operator_08_webhook_service.crd.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_10_kube-rbac-proxy-config.yaml
  install/0000_30_machine-api-operator_10_service.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  install/0000_30_machine-api-operator_12_clusteroperator.yaml
  install/0000_90_machine-api-operator_03_servicemonitor.yaml
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, lgtm

#739 Bug 1876469: Fix link on MachineSet Spec Metadata description
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  pkg/apis/machine/v1beta1/machineset_types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#742 Validate AWS instance tenancy in webhook
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, lgtm

#624 OCPCLOUD-898 - Use klog/controller runtime-logger in mao
  cmd/machine-api-operator/client_builder.go
  cmd/machine-api-operator/helpers.go
  cmd/machine-api-operator/main.go
  cmd/machine-api-operator/start.go
  cmd/machine-healthcheck/main.go
  go.mod
  go.sum
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/operator/baremetal_pod.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/sync.go
  pkg/util/machines/machines.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/modules.txt
Labels: approved, lgtm
