Repository openshift/machine-api-operator, pull requests merged in 2020-08, with the labels that each got.

#663 Update default user data to be worker-user-data-managed
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, lgtm

#659 Set default clusterID labels only on machine
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, lgtm

#606 Add alerting docs
  docs/user/Alerts.md
Labels: approved, lgtm, retest-not-required-docs-only

#662 Bug 1861695: Update defaultGCPDiskImage
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#666 BUG 1865779: Ensure MHC duration fields include units
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#670 RegisterFailedInstanceUpdate should update failedInstanceUpdateCount
  pkg/metrics/metrics.go
Labels: approved, lgtm

#669 Bug 1866719: Keep machine.nodeRef even if node was marked for deletion
  pkg/controller/nodelink/nodelink_controller.go
  pkg/controller/nodelink/nodelink_controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#665 Bug 1861974: [vSphere] Improve vSphere webhook
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#632 Add support for optional provisioning networks on Baremetal platforms
  install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/sync.go
Labels: approved, lgtm

#674 baremetal: configure containers with provisioning_ip
  pkg/operator/baremetal_pod.go
Labels: approved, lgtm

#675 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#679 BUG 1867262: Bump GCP provider dependency to include projectID field in NetworkInterface
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#676 Bug 1810443: Don't collect machine metrics if machine-controller not running
  pkg/metrics/metrics.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#657 Bug 1862998: baremetal: Deploy ironic with HTTP basic_auth
  go.mod
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/sync.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#680 BUG 1862556: Ensure that negative values for maxUnhealthy do not produce events
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#668 BUG 1827307: Default MachineSet replicas to 1
  hack/fetch_ext_bins.sh
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  pkg/apis/machine/v1beta1/machineset_types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#560 Bug 1840782: Update conditions under which metal3 pod would be deployed
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#689 Bug 1873234: Manage ownership hand-off of metal3 between MAO and CBO for upgrade and downgrade
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/operator.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
