Repository openshift/machine-api-operator, pull requests merged in 2020-12, with the labels that each got.

#762 Bug 1902253: Ensure zero value of remediationsAllowed is printed
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#767 Bug 1880787: Remove changes required to deploy metal3 pods from MAO
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
  install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/baremetal_config.go
  pkg/operator/baremetal_pod.go
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#768 Ensure provider dependencies are up to date
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#688 Don't use external remediation on failed Machines
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
Labels: approved, lgtm

#769 Add missing default profile annotation
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
Labels: approved, lgtm

#759 Bug 1880161: Set retry timeout for actuator.Update() failures
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#766 Update RBAC to enable access to machineconfig object for the baremetal controller
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, lgtm

#755 add mapi_machinehealthcheck_short_circuit metric
  docs/dev/metrics.md
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/metrics/machinehealthcheck.go
Labels: approved, lgtm

#775 Add missing default cluster profile annotation
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_09_security_context_constraint.yaml
Labels: approved, lgtm

#765 Bug 1882608: Add warning when govcloud and spot are enabled in Azure
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#764 Bug 1869320: [release-4.5] [vSphere] Reduce sync period to 10 minutes
  cmd/vsphere/main.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#743 add bound serviceaccount token to machine-controller
  pkg/operator/sync.go
Labels: approved, lgtm

#642 Refactor webhook syncronization to work with library-go implementation
  go.mod
  go.sum
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/modules.txt
Labels: approved, lgtm

#771 Update kubectl dep
  go.mod
  go.sum
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/modules.txt
Labels: approved, lgtm

#732 Bug 1882723: vSphere: Create warning on invalid specs and remove defaults
  hack/fetch_ext_bins.sh
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/controller/vsphere/reconciler.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#673 Bug 1805639: Validate credentialsSecret
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
  pkg/apis/machine/v1beta1/v1beta1_suite_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#772 Bug 1903733: MachineSet: Prefer to delete non-Running machines during scale down
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/delete_policy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#776 Bug 1907380: Reduce verbosity of kube-rbac-proxy logging
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
