Repository openshift/machine-api-operator, pull requests merged in 2020-05, with the labels that each got.

#575 Bug 1808971: Machine status shows "running" when an instance was terminated
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#580 BUG 1831577: Allow Machine API to create Service Linked Role for Spot instances
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#578 Bug 1829408: Reconcile machine power state annotation
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#586 Bug 1796412: cluster-reader is unable to view machine resources
  config/cluster-reader-rbac.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#592 Bug 1796412: cluster-reader is unable to view machine resources
  config/cluster-reader-rbac.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#585 Bug 1833256: [vSphere] Fail machine if multiple resource pools found
  pkg/controller/vsphere/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#593 Bug 1838504: [vSphere] Fail machine on invalid provider spec values
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#596 Bug 1839694: [vSphere] Add ability to read port from provider config
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/util.go
  pkg/controller/vsphere/util_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#599 Bug 1840552: Ensure status patch is after annotation patch when setting phase
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#597 Bug 1840665: [vSphere] Get insecure flag from provider config
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/session/session_test.go
  pkg/controller/vsphere/util.go
  pkg/controller/vsphere/util_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
