Repository openshift/machine-api-operator, pull requests merged in 2020-04, with the labels that each got.

#512 Add support for passing disk devices to vsphere machines
  pkg/apis/vsphereprovider/v1alpha1/vsphereproviderconfig_types.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm, size/L

#545 vsphere ipi: replace .Name() with .ObjectName()
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, lgtm

#546 [OCPCLOUD-815] Use MachineSet controller from MAO image
  Dockerfile
  Dockerfile.rhel7
  go.mod
  pkg/operator/baremetal_test.go
  pkg/operator/config.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm

#549 Bug 1810443: Rephrase MachineWithNoRunningPhase message
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#548 Bug 1817860: Drop non existent object from relatedResources
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#551 Add alexander-demichev to OWNERS
  OWNERS
Labels: approved, lgtm

#550 Bug 1702089: Move embedded ObjectMeta to machine api to provide open api schema
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  pkg/apis/machine/v1beta1/common_types.go
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/apis/machine/v1beta1/machineset_types.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/apis/vsphereprovider/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/machineset_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#555 BUG 1823308: Allow machine-api-termination-handler to use hostnetwork SCC
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#559 BUG 1824497: Enable error checks to unwrap errors
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/openshift_controller_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#534 Add User FAQ
  FAQ.md
Labels: approved, lgtm

#562 BUG 1825851: Ensure malformed IntOrPercent returns error
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#561 Bug 1824943: check minimum available time in waitForDeploymentRollout
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  pkg/util/conditions/conditions.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#566 FAQ: Fix URL to machine-instance-lifecycle.md
  FAQ.md
Labels: approved, lgtm

#557 BUG 1815219: Allow machines to have encrypted EBS volumes with non-default key
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#564 BUG 1826017: Switch to Go errors instead of github.com/pkg/errors
  go.mod
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/status.go
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/util.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#558 Bug 1822665: Find vm by name if UUID search fails
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/session/session_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#552 BUG 1769004: Make Machine/MachineSets structural
  go.mod
  go.sum
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/common_types.go
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/apis/machine/v1beta1/machine_types_test.go
  pkg/apis/machine/v1beta1/machineset_types_test.go
  pkg/apis/machine/v1beta1/v1beta1_suite_test.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#572 Bug 1822200: Add ec2:DescribeDhcpOptions permission request
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#574 Bug 1804464: Relax timeout for metrics availability alerts
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#567 Bug 1827601: vSphere - Return error on empty task reference
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/session/session_test.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#563 Bug 1827593: Check if tag is already attached to vm
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#573 Bug 1829333: vSphere - Don't reconcile power state
  pkg/controller/vsphere/reconciler.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#568 Bug 1826983: Fix External DHCP range values for Baremetal configuration
  pkg/operator/baremetal_config.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
