Repository openshift/machine-api-operator, pull requests merged in 2021-02, with the labels that each got.

#701 Machine: Set ErrorReason when entering Failed phase
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, lgtm

#794 Return a valid error message when multiple templates are found
  pkg/controller/vsphere/reconciler.go
Labels: approved, lgtm

#782 Bug 1912531: 4.6: Update kubectl dep
  go.mod
  go.sum
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#785 fix the link to capbm
  README.md
Labels: approved, lgtm

#799 [OCPCLOUD-1066] Makefile fix
  Makefile
  README.md
  docs/dev/hacking-guide.md
  hack/ci-test.sh
  hack/go-fmt.sh
  hack/go-gen.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/goimports.sh
  hack/gosec.sh
  hack/imagebuilder.sh
  hack/owner_reset.sh
Labels: approved, lgtm

#804 Bug 1929645: Remove "kubevirt-machine-controllers" image from release 4.7
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#801 Update capz for disk encryption
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#806 Enable Junit reports for CI unit tests runs
  hack/ci-test.sh
Labels: approved, lgtm

#691 [OCPCLOUD-930]: Aggregate operator errors before failing to sync
  pkg/operator/sync.go
Labels: approved, lgtm
