Repository openshift/machine-api-operator, pull requests merged in 2021-06, with the labels that each got.

#868 Bug 1967662: change provider config to look at PlatformStatus.Type
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#863 Correct doc namespace err and misspellings
  README.md
  docs/dev/hacking-guide.md
Labels: approved, lgtm, ok-to-test

#870 Bug 1965080: Update AWS permissions to reflect requirements for load balancers
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm

#873 remove kubevirt images and references
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm

#807 [OCPCLOUD-921] add alert for machine with long deletion phase
  docs/user/Alerts.md
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, lgtm

#831 add in-container vendoring
  Makefile
  hack/go-mod.sh
Labels: approved, lgtm

#878 install/0000_90_machine-api-operator_04_alertrules: Use '!~' for MachineWithNoRunningPhase
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, lgtm

#850 Bug 1953063: Update default AWS instance types
  docs/examples/machine.yaml
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#864 Fixing label from clutserapi to clusterapi
  install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
Labels: approved, lgtm, ok-to-test

#879 [OCPCLOUD-1173] Add related objects to Cluster Operator
  install/0000_30_machine-api-operator_12_clusteroperator.yaml
Labels: approved, lgtm

#880 add a nodelink controller doc to describe its basic working
  docs/user/nodelink-controller.md
Labels: approved, lgtm

#803 fix logging message
  pkg/controller/machineset/controller.go
Labels: approved, lgtm

#875 Add kubevirt images
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: approved, lgtm
