Repository openshift/machine-api-operator, pull requests merged in 2021-07, with the labels that each got.

#882 Bug 1977369: Prevent machine from stucking in Deleting phase on vSphere if related node object not found
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#889 [OCPCLOUD-1153] add a tombstones manifest to the install directory
  install/0000_99_machine-api-operator_00_tombstones.yaml
Labels: approved, lgtm

#887 Backport MHC pause feature from cluster API
  pkg/apis/machine/v1beta1/consts.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/util/annotations/helpers.go
Labels: approved, lgtm

#886 [OCPCLOUD-922] add alert for mhc in short circuit
  docs/user/Alerts.md
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, lgtm

#890 Bug 1980930: Update the default durations for MAO leader election operations
  cmd/machine-api-operator/helpers.go
  cmd/machine-api-operator/start.go
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/util/durations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
