Repository openshift/machine-api-operator, pull requests merged in 2021-08, with the labels that each got.

#893 Bug 1988032: add cvo ha annotations to tombstones
  install/0000_99_machine-api-operator_00_tombstones.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#897 Bug 1989980: Create event only if the machine was modified
  pkg/controller/vsphere/actuator.go
  pkg/controller/vsphere/actuator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#894 Bug 1990432: Make sure nodes don't have attached volumes before vm deletion
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#902 Bug 1975296: Respect MaxUnhealthy limit for external remediation
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#869 Bug 1957609: Warn when an AWS tag name is duplicated
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
