Repository openshift/machine-api-operator, pull requests merged in 2021-09, with the labels that each got.

#888 Add webhook to ensure that only ID references AMI
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: lgtm, approved

#912 Fix user-agent in vCenter sessions list
  pkg/controller/vsphere/session/session.go
Labels: lgtm, approved

#916 fix time values in alert doc
  docs/user/Alerts.md
Labels: lgtm, approved

#858 [release-4.7] Bug 1933586: Make sure phase is always set before creation
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: lgtm, approved, lifecycle/stale, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#914 [OCPCLOUD-855] add a distinct status message for NoOp mode
  docs/user/machine-api-operator-overview.md
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/sync.go
Labels: lgtm, approved

#871 Add the IBMCloud cluster api controller
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/fixtures/images.json
Labels: lgtm, approved

#883 Add service account names to gcp credentials request manifest
  go.mod
  go.sum
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  vendor/golang.org/x/oauth2/authhandler/authhandler.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/errors.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: lgtm, approved

#892 Adds ibmcloud mapi controller to image ref
  install/image-references
Labels: lgtm, approved

#899 docs/user/nodelink-controller: Fix name/namespace order for machine.openshift.io/machine
  docs/user/nodelink-controller.md
Labels: lgtm, approved

#911 Bug 2003545: Remove "kubevirt-machine-controllers" image from release 4.9
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved

#915 Remove ironic-inspector reference in MAO
  install/image-references
Labels: lgtm, approved

#909 Bug 1999425: MaxUnhealthy should not be a string type
  go.mod
  go.sum
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#908 Bug 1999585: [release-4.8] add alert for machine with long deletion phase
  docs/user/Alerts.md
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#920 Add logging for possible error during vsphere session creation
  pkg/controller/vsphere/session/session.go
Labels: lgtm, approved

#922 Vsphere sessions check: fix log string formatting
  pkg/controller/vsphere/session/session.go
Labels: lgtm, approved
