Repository openshift/machine-api-operator, pull requests merged in 2021-01, with the labels that each got.

#780 Bug 1905709: Drain: ignore gracePeriod on unreachable kublets
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#781 Bug 1907380: Reduce verbosity of kube-rbac-proxy logging for operator
  install/0000_30_machine-api-operator_11_deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#774 Bug 1915473: Annotate manifests for single-node-developer cluster profile
  hack/gen-crd.sh
  install/0000_30_machine-api-operator_00_namespace.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  install/0000_30_machine-api-operator_08_webhook_service.crd.yaml
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_10_kube-rbac-proxy-config.yaml
  install/0000_30_machine-api-operator_10_service.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  install/0000_30_machine-api-operator_12_clusteroperator.yaml
  install/0000_90_machine-api-operator_03_servicemonitor.yaml
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#788 Bug 1915962: Add exclusion annotation for machine health check on ROKS
  install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#787 Bug 1915114: allow machine-api-controllers to access configmaps in openshift-config-managed
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#789 Bug 1918524: Update Makefile to work with containers
  Makefile
  hack/ci-test.sh
  hack/fetch_ext_bins.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#763 Bug 1890452: Bump Azure dependency to include BYOK encryption fields
  go.mod
  go.sum
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
