Repository openshift/machine-api-operator, pull requests merged in 2021-05, with the labels that each got.

#854 Bug 1918101: Fix deleting for machine stucked in provisioning state on vSphere
  pkg/controller/vsphere/reconciler.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#855 Bug 1954177: update AdmissionReviewVersions to v1
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#862 Bug 1954177: add constant variables back into machine v1beta1
  pkg/apis/machine/v1beta1/consts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#830 Bug 1939054: Disable startup timeout for Spot MHC
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
  install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
  pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#866 Bug 1948719: update controller-runtime dependency
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/selector.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/multi.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
