Repository openshift/machine-api-operator, pull requests merged in 2021-03, with the labels that each got.

#811 Ensure daemonset conforms to standards
  pkg/operator/sync.go
Labels: approved, lgtm

#817 Bug 1934216: reuse mgr client in webhooks
  cmd/machineset/main.go
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#812 [release-4.6] Bug 1933676: Cherry-pick: Azure disconnected reject publicIP setting
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
  pkg/apis/machine/v1beta1/machineset_webhook.go
  pkg/apis/machine/v1beta1/machineset_webhook_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#810 Bug 1910318: [OCPCLOUD-931] Add condition to show actuator exists output on machine status
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  pkg/apis/machine/v1beta1/condition_consts.go
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/apis/machine/v1beta1/v1beta1_suite_test.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#809 Bug 1921892: Ensure manager stops before ending the test
  pkg/controller/machineset/machineset_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#791 remove code
  cmd/machine-healthcheck/main.go
Labels: approved, lgtm, ok-to-test

#818 Bug 1929721: Add SecurityProfile.EncryptionAtHost parameter to enable host-based VM encryption
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#825 Add resource limit to pods
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: approved, lgtm

#823 Bug 1923823: Improve TLS configuration for Kube RBAC Proxy
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#826 install/0000_90_machine-api-operator_04_alertrules: Drop MachineAPIOperatorDown
  docs/user/Alerts.md
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: approved, lgtm

#827 Bug 1938493: Revert "Add resource limit to pods"
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#802 Add service account names to credentials request manifest
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, lgtm

#829 Bug 1910318: Ensure original conditions aren't mutated during reconcile
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#824 BUG 1932154: add warning for missing IAMInstanceProfile in AWS
  pkg/apis/machine/v1beta1/machine_webhook.go
  pkg/apis/machine/v1beta1/machine_webhook_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#815 Bug 1883993: vSphere, detach virtual disks before virtual machine destroy if node not available
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/machine_scope_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#836 Don't mount service account token in termination daemonset
  pkg/operator/sync.go
Labels: approved, lgtm

#833 Update GCP default disk image to include ignition v3
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, lgtm
