Repository openshift/machine-api-operator, pull requests merged in 2021-10, with the labels that each got.

#924 podsecurity: enforce privileged for openshift-machine-api namespace
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: lgtm, approved

#913 Bug 1986237: modify MachineNotYetDeleted alert to ignore pod
  docs/user/Alerts.md
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#939 Update Dockerfile with correct image and go version
  Dockerfile
Labels: lgtm, approved

#935 Bug 2013895: Bump Azure dependency to include new fields
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/machine/install.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/doc.go
  vendor/github.com/openshift/api/machine/v1beta1/generated.pb.go
  vendor/github.com/openshift/api/machine/v1beta1/generated.proto
  vendor/github.com/openshift/api/machine/v1beta1/register.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/oauth/v1/generated.proto
  vendor/github.com/openshift/api/oauth/v1/types.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
