Repository openshift/machine-api-operator, pull requests merged in 2021-12, with the labels that each got.

#964 README: improve Controllers section indentation/naming
  README.md
Labels: lgtm, approved

#965 Bug 2025697: [release-4.9]: Bump CAPZ API
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#927 OCPCLOUD-1252: Add validation webhook for guestAccelerators on GCP
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved

#966 Machine API Provider OpenStack Feature Gate
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator.go
Labels: lgtm, approved

#968 Manifest syncing between install and vendored openshift/api
  Makefile
  hack/crds-sync.sh
  hack/verify-diff.sh
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
Labels: lgtm, approved

#950 Bug 2031858: stop using beta pre-defined role for compute.targetPools
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#926 AlibabaCloud: adding alibaba cloud platform
  go.mod
  go.sum
  install/0000_30_machine-api-operator_00_credentials-request.yaml
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
  pkg/operator/operator_test.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: lgtm, approved

#970 Bug 2027896: [release-4.8] Add support for Azure Marketplace Images
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_apirequestcount.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#960 Bug 2011668: Improve powerOff task handling during machine deletion on vsphere platform
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#972 Bug 2034484: feat: updated library-go
  cmd/machine-api-operator/start.go
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  go.mod
  go.sum
  pkg/util/durations.go
  pkg/util/leaderelection.go
  pkg/webhooks/v1beta1_suite_test.go
  vendor/github.com/openshift/library-go/pkg/config/clusterstatus/clusterstatus.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/modules.txt
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/kubernetes_patch.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#973 Bug 2034879: Enforce unique names for lifecycle hooks via webhooks
  go.mod
  go.sum
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
