Repository openshift/machine-api-operator, pull requests merged in 2021-04, with the labels that each got.

#822 Update hacking-guide.md with imagebuilder troubleshooting instructions
  docs/dev/hacking-guide.md
Labels: approved, lgtm

#842 Fix GCP default image name
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, lgtm

#839 Vsphere enable autoscaling from/to zero
  cmd/vsphere/main.go
  go.mod
  pkg/controller/vsphere/machineset/controller.go
  pkg/controller/vsphere/machineset/controller_suite_test.go
  pkg/controller/vsphere/machineset/controller_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/modules.txt
Labels: approved, lgtm

#847 Bug 1948471: Add release inclusion annotations to external remediation cluster role
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#835 Bug 1880757: Add missing permission for target group de-registration
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#849 Bug 1910318: Ensure conditions are correctly copied before annotations are patched
  pkg/controller/machine/controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#851 Bug 1951029: Drainer panics on missing context for node patch
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#857 Bug 1925276: Make sure phase is always set before creation
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#808 [release-4.6] Bug 1916772: Inject the cluster-wide proxy environment variables in the baremetal pod
  pkg/operator/baremetal_pod.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#844 Add management workload annotations
  install/0000_30_machine-api-operator_00_namespace.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: approved, bugzilla/valid-bug, lgtm

#856 Bug 1954610: Update GCP default image to match 4.7 release
  pkg/apis/machine/v1beta1/machine_webhook.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#860 Bug 1955554: Webhook filter should check for both mutating and validating webhooks
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
