Repository openshift/machine-api-operator, pull requests merged in 2021-11, with the labels that each got.

#944 Bug 2005052: Deny selector updates via webhook to prevent leaked machines
  pkg/webhooks/machineset_webhook.go
  pkg/webhooks/machineset_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#947 Rewrite rollout checks to requeue and not block reconciles
  pkg/operator/operator.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
Labels: lgtm, approved

#948 Add powervs-machine-controllers to images configmap
  install/0000_30_machine-api-operator_01_images.configmap.yaml
Labels: lgtm, approved

#949 GCP CI runs are complaining about APIs not being enabled
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved

#953 Bug 2022838: GCP CI runs are complaining about APIs not being enabled
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#954 Bug 2022839: GCP CI runs are complaining about APIs not being enabled
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#955 Bug 2022840: GCP CI runs are complaining about APIs not being enabled
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#945 [OCPCLOUD-1350] Implement machine pre-drain and pre-terminate deletion hooks
  go.mod
  go.sum
  install/0000_30_machine-api-operator_02_machine.crd.yaml
  install/0000_30_machine-api-operator_03_machineset.crd.yaml
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/util/lifecyclehooks/sort.go
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  pkg/webhooks/v1beta1_suite_test.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#946 [OCPCLOUD-1351] Implement conditions for Machine Deletion Hooks reporting
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: lgtm, approved

#957 Remove unused files
  Makefile
  config/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  config/0000_05_config-operator_01_featuregate.crd.yaml
  config/kubemark-config-infra.yaml
  config/kubemark.yaml
  config/kubemark_rbac.yaml
  config/kustomization.yaml
  config/machine-api-operator-deployment.yaml
  config/machine-api-operator-patch.yaml
  config/machineset.yaml
  config/prometheusrule.crd.yaml
  config/servicemonitor.crd.yaml
  kustomization.yaml
  pkg/webhooks/machine_types_test.go
  pkg/webhooks/machineset_types_test.go
  pkg/webhooks/v1beta1_suite_test.go
  tools.go
Labels: lgtm, approved
