Repository openshift/machine-api-operator, pull requests merged in 2022-06, with the labels that each got.

#998 Bug 2094196: Added webhook support for PowerVS platform
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  pkg/webhooks/machineset_webhook.go
  pkg/webhooks/machineset_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1023 Bug 2082667: Separate controller for the node draining
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/drain_controller.go
  pkg/controller/machine/drain_controller_test.go
  pkg/controller/machine/machine_controller_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1028 Update revendoring tool
  hack/push-updates.sh
Labels: lgtm, approved
