Repository openshift/machine-api-operator, pull requests merged in 2022-10, with the labels that each got.

#1072 OCPBUGS-1274: add tolerations to termination handler
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1076 Update default Azure image to use image galleries
  pkg/webhooks/machine_webhook.go
Labels: lgtm, approved

#1073 Updating ose-machine-api-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel
  pkg/controller/machine/actuator.go
  pkg/controller/vsphere/machine_scope.go
  pkg/metrics/machinehealthcheck.go
  pkg/operator/status.go
Labels: lgtm, approved

#1074 OCPBUGS-2151: Don't degrade when workers not expected
  pkg/operator/sync.go
  pkg/operator/sync_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1062 OCPCLOUD-1131: Add DescribeInstanceTypes permission for AWS provider
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved

#1018 Show warnings if provider specs have invalid GroupVersionKind
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved

#1065 [release-4.10] OCPBUGS-957: Change "create" sequence with powering on the vm after clone
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug
