Repository openshift/machine-api-operator, pull requests merged in 2022-08, with the labels that each got.

#1049 update windows helper functions
  pkg/util/windows/helpers.go
  pkg/util/windows/helpers_test.go
Labels: lgtm, approved

#1047 Bug 2087981: Change "create" sequence with powering on the vm after clone
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1051 Bug 2115308: Ensure failed drains are subject to exponential backoff
  pkg/controller/machine/controller.go
  pkg/controller/machine/drain_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1055 add a helper function to detect windows os
  pkg/util/windows/helpers.go
  pkg/util/windows/helpers_test.go
Labels: lgtm, approved

#1050 Change the git command
  docs/dev/hacking-guide.md
Labels: lgtm, approved

#1053 Bug 2111972: operator NS manifest: Set empty openshift.io/run-level
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1056 OCPBUGS-268: vSphere - enable steal time accounting
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, qe-approved, jira/valid-bug
