Repository openshift/machine-api-operator, pull requests merged in 2022-05, with the labels that each got.

#1012 Don't force a requeue after updating Status.Phase
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: lgtm, approved

#996 Skip validation if we just remove the finalizer
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved

#1013 Bug 2083237: Set vCenter client request timeout
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/session/session_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1016 Bug 2059338: Add template HW version detection during clone
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
