Repository openshift/machine-api-operator, pull requests merged in 2022-01, with the labels that each got.

#974 Bug 2034563: validate azure ephemeral storage location and caching type
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#959 Bug 2001008: Change default cloneMode to fullClone.
  pkg/controller/vsphere/reconciler.go
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#975 Bug 2033390: connect real MAPO images
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#961 Bug 1918005: Use known vSphere cluster to uniquely identify networks.
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#978 Bug 2040620: Rename MAPO image
  install/0000_30_machine-api-operator_01_images.configmap.yaml
  install/image-references
  pkg/operator/config_test.go
  pkg/operator/fixtures/images.json
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#981 Bug 2041971: Bump library-go to fix mutating webhook reconcile
  go.mod
  go.sum
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#982 fix readme after migrating from cluster-api-provider-*
  README.md
Labels: lgtm, approved
