Repository openshift/machine-api-operator, pull requests merged in 2022-07, with the labels that each got.

#1029 [OCPCLOUD-1584] Add webhook validations for Azure boot diagnostics
  go.mod
  go.sum
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#1031 Bug 2101880: operator NS manifest: Set empty openshift.io/run-level
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1030 add utility functions for windows powershell tags
  pkg/util/windows/helpers.go
  pkg/util/windows/helpers_test.go
Labels: lgtm, approved

#1024 Migrate delete annotation to match upstream CAPI annotation
  FAQ.md
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/delete_policy_test.go
Labels: lgtm, approved

#1019 Bug 1994820: Degrade operator on cluster bootstrap if not all Machines are Running
  cmd/machine-api-operator/start.go
  go.mod
  go.sum
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1/fake/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1/fake/fake_machine_client.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machine.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machine_client.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machinehealthcheck.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machineset.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1027 Bug 2097153: change ListTags call to ListTagsForCategory
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1038 Bug 2104642: fix the Machine validation webhook for nutanix providerSpec
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, qe-approved

#1039 [release-4.11] Bug 2105382: Add a validation webhook for Nutanix MachineProviderConfig
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, qe-approved

#1040 Bug 2107578: Fix while setting default processor value for Power VS platform
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1037 Bug 2101736: allow to remove finalizers
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1042 Bug 2109258: add more support for old delete annotation
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/delete_policy_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1045 Bug 2110501: Revert "Bug 2101880: operator NS manifest: Set empty openshift.io/run-level"
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1044 Bug 2110505: revert: Bug 2101880: operator NS manifest: Set empty openshift.io/run-level
  install/0000_30_machine-api-operator_00_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, staff-eng-approved
