Repository openshift/machine-api-operator, pull requests merged in 2022-09, with the labels that each got.

#1060 Release leader election lease when shutting down
  cmd/machine-api-operator/start.go
Labels: lgtm, approved

#1059 [OCPBUGS-380] Ensure the phase transition metric only updates when the phase changes
  pkg/controller/machine/controller.go
Labels: lgtm, approved

#1061 Bug 2101736: Ignore managed fields during finalizer removal
  pkg/webhooks/machine_webhook.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1063 Add tag and category id to the caching client log messages
  pkg/controller/vsphere/session/tag_ids_caching_client.go
Labels: lgtm, approved

#1066 Only drain a single control plane machine at once
  pkg/controller/machine/drain_controller.go
  pkg/controller/machine/drain_controller_test.go
Labels: lgtm, approved

#1068 OCPBUGS-519: update error message for disconnected installation validation
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  pkg/webhooks/machineset_webhook_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug

#1067 Restrict creating Power VS machine with negative processor and memory
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved
