Repository openshift/machine-api-operator, pull requests merged in 2023-12, with the labels that each got.

#1183 NO-JIRA: Update OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference

#1174 OCPVE-778: annotate cloud credentials request
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/valid-reference

#1184 OCPBUGS-18339: Update reference URL
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#1186 OCPBUGS-24047: Update reference URL
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1188 OCPBUGS-24277: Update reference URL
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1192 OCPBUGS-25735: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1193 OCPBUGS-25734: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
