Repository openshift/machine-api-operator, pull requests merged in 2023-06, with the labels that each got.

#1141 OCPBUGS-10719: [release-4.11] - manual cp #1057 - machines stuck in provisioned or provisioning
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/session/session.go
  pkg/controller/vsphere/session/session_test.go
  pkg/controller/vsphere/session/tag_ids_caching_client.go
  pkg/controller/vsphere/session/test_ids_caching_client_test.go
  pkg/controller/vsphere/util.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1140 CCO-321: Add support for feature-gating specific providers
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/sync.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1149 MachineAPIOperatorMetricsCollectionFailing to warning
  install/0000_90_machine-api-operator_04_alertrules.yaml
Labels: lgtm, approved
