Repository openshift/machine-api-operator, pull requests merged in 2023-07, with the labels that each got.

#1150 Bump openshift/api package
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/custom.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/custom.dns.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/custom.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/.codegen.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_olm-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_olm-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/custom.olm.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/register.go
  vendor/github.com/openshift/api/operator/v1alpha1/techpreview.olm.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_olm.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/.codegen.yaml
  vendor/github.com/openshift/api/route/v1/custom.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/techpreview.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_roundrobin.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved

#1151 Add feature gate for disabling the MHC controller
  cmd/machine-api-operator/start.go
  go.mod
  go.sum
  install/0000_30_machine-api-operator_09_rbac.yaml
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  pkg/operator/sync_test.go
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/modules.txt
Labels: lgtm, approved

#1154 reconcile status when the clusteroperator changes
  cmd/machine-api-operator/start.go
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/operator/operator.go
Labels: lgtm, approved

#1156 Fix data race conditions in unit tests
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/controller/machineset/controller_test.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/nodelink/nodelink_controller_test.go
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/machineset/controller_suite_test.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/util_test.go
  pkg/webhooks/v1beta1_suite_test.go
Labels: lgtm, approved

#1157 MGMT-13630: Add Azure Confidential VM and TrustedLaunch for VMs webhook validations
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, jira/valid-reference

#1155 OCPBUGS-16307: default instance type for Azure based on the architecture (+ gcp)
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  pkg/webhooks/machineset_webhook_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1159 install/0000_99_machine-api-operator_00_tombstones: Drop obsolete file
  install/0000_99_machine-api-operator_00_tombstones.yaml
Labels: lgtm, approved

#1160 OCPBUGS-16925: only attempt to remove finalizers if staticIPFeatureGateEnabled
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
