Repository openshift/machine-api-operator, pull requests merged in 2023-01, with the labels that each got.

#1096 OCPBUGS-4566: Append annotations from machine template spec to the node
  FAQ.md
  pkg/controller/nodelink/nodelink_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1101 OCPBUGS-5018: machine-api-termination-handler: run DaemonSet only on Linux
  pkg/operator/sync.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1106 Add warning for unknown fields when unmarshaling the provider spec
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved

#1107 [OCPBUGS-4725]: Short circuit misfiring
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
Labels: lgtm, approved, qe-approved

#1102 MGMT-12838: add webook validation for shieldedInstanceConfig on GCP
  go.mod
  go.sum
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  vendor/github.com/openshift/api/config/install.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_insights-operator_00-insightsoperator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.console.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_insights.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#1111 Remove the openstack-machine-controllers image
  install/image-references
Labels: lgtm, approved
