Repository openshift/machine-api-operator, pull requests merged in 2023-02, with the labels that each got.

#1116 OCPBUGS-3275: Update machinehealthcheck dropping log from Error to Warning
  pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1115 OCPCLOUD-1852: Bump k8s dependencies to 1.26; go 1.19
  Dockerfile
  Makefile
  cmd/machine-api-operator/start.go
  cmd/machine-api-operator/version.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
  cmd/vsphere/main.go
  pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync_test.go
Labels: lgtm, approved, jira/valid-reference

#1118 OCPBUGS-6063: Forcefully delete unevicted pods within vSphere machine deletion procedure
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/util.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1117 Add Machine webhook to validate the new fields of NutanixMachineProviderConfig
  go.mod
  go.sum
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#1121 OCPBUGS-6063: Add missed permission for a pod deletion on vsphere platform
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
