Repository openshift/machine-api-operator, pull requests merged in 2023-08, with the labels that each got.

#1152 OCPCLOUD-2014: Switch Azure credentials request to use explicit permissions
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#1162 OCPBUGS-17919: [Azure] MAO Missing DiskEncryptionSet read permissions
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1163 OCPBUGS-18338: Fix CI by running tests natively by default
  Makefile
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1164 OCPBUGS-17090: Set logger for controller runtime
  cmd/machine-healthcheck/main.go
  cmd/machineset/main.go
  cmd/nodelink-controller/main.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
