Repository openshift/machine-api-operator, pull requests merged in 2023-03, with the labels that each got.

#1122 OCPCLOUD-1778: Add None and External platform type explicit handling
  pkg/operator/config.go
  pkg/operator/config_test.go
Labels: lgtm, approved, jira/valid-reference

#1126 OCPBUGS-7249: Fix zone tag value reconciliation for vSphere machines
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1120 [release-4.12] OCPBUGS-7882: Block machine deletion if extra disks are attached
  install/0000_30_machine-api-operator_09_rbac.yaml
  pkg/controller/vsphere/machine_scope.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/util.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1128 OCPBUGS-10591: Fix empty component version
  hack/go-build.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1129 CCO-321: Add service account name to Azure credentials request
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/valid-reference
