Repository openshift/machine-api-operator, pull requests merged in 2024-08, with the labels that each got.

#1266 CORS-3546: Nutanix: add gpus and dataDisks support
  go.mod
  go.sum
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  vendor/github.com/openshift/api/Dockerfile.ocp
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1272 OCPBUGS-37154: Added Permisions for Azure Capacity Reservation
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1274 OCPCLOUD-2565: Machine controller feature gating
  cmd/vsphere/main.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/machine_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#1240 OCPBUGS-31777: Updates message verbs to use %q where appropriate
  pkg/controller/machine/controller.go
  pkg/controller/vsphere/actuator.go
Labels: lgtm, approved, lifecycle/stale, jira/valid-bug, jira/valid-reference

#1279 CORS-3648: Add the hyperdisk-balanced disk type
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
