Repository openshift/machine-api-operator, pull requests merged in 2024-01, with the labels that each got.

#1189 OCPBUGS-25303: Update reference URL
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1178 OCPCLOUD-1725: Add GCP custom roles
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/valid-reference

#1198 OCPBUGS-25304: Update Reference URL
  pkg/controller/vsphere/reconciler.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1191 OCPBUGS-24998: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1202 OCPBUGS-23544: Add AddWithActuatorOpts to allow overriding Machine controller options
  pkg/controller/machine/controller.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1203 OCPBUGS-23544: Set --max-concurrent-reconciles=10 for Azure machine controller
  pkg/operator/sync.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1194 OCPBUGS-25165: Add Snyk file to exclude vendor directory on scan
  .snyk
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1206 OCPBUGS-27385: Add useExternalIp gcp permission
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1158 CFE-684: Update GCPCloudCredentials with TagUser role
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#1211 OCPBUGS-28230: add FallbackToLogsOnError for easier debugging
  install/0000_30_machine-api-operator_11_deployment.yaml
  pkg/operator/sync.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1204 SPLAT-1386: reconcile additional tags assigned to machine
  Dockerfile
  docs/user/vsphere/tags.md
  pkg/controller/vsphere/actuator_test.go
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/controller/vsphere/session/tag_ids_caching_client.go
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1212 OCPBUGS-25193: Add additional vnet join permission for Azure
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1215 OCPBUGS-26119: Add build tags to tools.go file to solve linting issues when running Snyk scans
  tools.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
