Repository openshift/machine-api-operator, pull requests merged in 2024-09, with the labels that each got.

#1284 OCPCLOUD-2703: OWNERS: update subcomponent
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1275 OCPCLOUD-2565: Updates operator to pass feature gates flags to Machine controllers
  cmd/machineset/main.go
  cmd/vsphere/main.go
  go.mod
  go.sum
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  vendor/github.com/openshift/library-go/pkg/features/features.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/event_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1287 OCPCLOUD-2565: Adds paused condition to MachineSet
  go.mod
  go.sum
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/controller_test.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/machineset/status.go
  pkg/util/conditions/gettersetter.go
  pkg/util/conditions/wrap.go
  pkg/util/testing/testing.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
Labels: lgtm, approved, jira/valid-reference

#1291 OCPBUGS-42388: Ensure deletion annotation takes priority and oldestPolicy can distinguish longer ages
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/delete_policy_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1294 OCPBUGS-42529: Updates paused condition messages
  pkg/controller/machine/controller.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/machineset_controller_test.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
