Repository openshift/machine-api-operator, pull requests merged in 2024-10, with the labels that each got.

#1295 NO-JIRA: Updates MachineSet tests to use GenerateName
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/machineset/machineset_controller_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/.gitignore
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/cleanup.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/conditions.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/logger.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/configmap.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/namespace.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/node.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/secret.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/service.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/tools.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1296 OCPCLOUD-2693: Added the AWS Capacity Reservation Webhook
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#1299 OCPBUGS-43481: fix: health probes paths and updated timing
  pkg/operator/sync.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1300 OCPBUGS-41502: vSphere klog initialization preventing verbose log messages
  cmd/vsphere/main.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1303 OCPBUGS-43821: install/0000_30_machine-api-operator_00_credentials-request: Set skipServiceCheck again for GCP
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
