Repository openshift/machine-api-operator, pull requests merged in 2025-05, with the labels that each got.

#1358 OCPBUGS-55424: Added skip for when config not multi nic
  test/e2e/vsphere/machines.go
  test/e2e/vsphere/multi-nic.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1363 OCPBUGS-55461: Revert "Added skip for when config not multi nic"
  test/e2e/vsphere/machines.go
  test/e2e/vsphere/multi-nic.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1361 OCPBUGS-55461: Fixes machineset paused condition nil pointer
  pkg/controller/machineset/controller.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1362 OCPBUGS-55720: fix: use patch for machine/machineset status
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/drain_controller.go
  pkg/controller/machineset/status.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1367 [release-4.19] OCPBUGS-55706: fix: use patch for machine/machineset status
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/drain_controller.go
  pkg/controller/machineset/status.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1365 OCPBUGS-55461: Changed machineset tests to be serial
  test/e2e/util.go
  test/e2e/vsphere/machines.go
  test/e2e/vsphere/multi-nic.go
  test/e2e/vsphere/util.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1370 OCPBUGS-56159: correct aws kms permissions
  install/0000_30_machine-api-operator_00_credentials-request.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1369 SPLAT-2082: Create e2e for vSphere vm-host zonal feature
  test/e2e/util.go
  test/e2e/vsphere/hostzonal.go
  test/e2e/vsphere/util.go
Labels: lgtm, approved, jira/valid-reference
