Repository openshift/machine-api-operator, pull requests merged in 2025-01, with the labels that each got.

#1316 OCPBUGS-46433: Add cluster-reader to controlplanemachinesets resource
  install/0000_30_machine-api-operator_09_rbac.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1320 OCPBUGS-43608: add webhook for fields that are not working
  pkg/webhooks/machine_webhook.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1322 [release-4.14] OCPBUGS-48245: VSphere: Handle cloned instance with lost taskID
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1290 SPLAT-1811: Add vSphere multi disk support
  cmd/machineset/main.go
  cmd/vsphere/main.go
  go.mod
  go.sum
  pkg/controller/vsphere/reconciler.go
  pkg/controller/vsphere/reconciler_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/status.go
  pkg/util/testing/testing.go
  pkg/webhooks/machine_webhook.go
  pkg/webhooks/machine_webhook_test.go
  pkg/webhooks/machineset_webhook_test.go
  vendor/github.com/openshift/api/.golangci.yaml
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_cluster_monitoring.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_clustermonitoring-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_clustermonitoring-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_clustermonitoring-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/monitoring/v1/types.go
  vendor/github.com/openshift/api/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_insights.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_clusterversion.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1323 SPLAT-1800: vSphere host zonal missing operator feature
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
